export const constants = {
  tools: [
    { title: 'JSON Beautifier', variant: 'default' },
    { title: 'HTML Viewer', variant: 'default' },
    { title: 'Number to Words', variant: 'default' },
    { title: 'SQL Formatter', variant: 'default' },
    { title: 'Image to Base64', variant: 'default' },
    { title: 'Base64 to Image', variant: 'default' },
    { title: 'HEX to Pantone', variant: 'default' },
    { title: 'Source Code Viewer', variant: 'default' },
    { title: 'Binary to Text', variant: 'default' },
    { title: 'JSON Viewer', variant: 'default' },
    { title: 'JSON Validator', variant: 'default' },
    { title: 'Base64 Decode', variant: 'default' },
    { title: 'Hex to Decimal', variant: 'default' },
    { title: 'XML Viewer', variant: 'default' },
    { title: 'XML to JSON', variant: 'default' },
    { title: 'Encryption-Decryption', variant: 'default' },
    { title: 'Excel to HTML', variant: 'default' },
    { title: 'CSS Validator', variant: 'default' },
    { title: 'XML Validator', variant: 'default' },
    { title: 'JavaScript Validator', variant: 'default' },
    { title: 'CSS Beautifier', variant: 'primary' },
    { title: 'ONLINE JSON EDITOR', variant: 'default' },
    { title: 'Decimal to Hex', variant: 'default' },
    { title: 'Binary to Decimal', variant: 'default' },
    { title: 'ASCII to Text', variant: 'default' },
    { title: 'Random Emoji Generator', variant: 'default' },
    { title: 'REM to PX Converter', variant: 'default' },
    { title: 'Incorrect Quotes Generator', variant: 'default' },
    { title: 'Lua Beautifier', variant: 'default' },
  ],
  newFundata: [
    { title: 'Flag Maker', variant: 'default' },
    { title: 'Code to ASCII', variant: 'default' },
    { title: 'Inches to Pixels', variant: 'default' },
    { title: 'Vertical Font Generator', variant: 'default' },
    { title: 'JSON MultiLine String', variant: 'default' },
    { title: 'JWT Decode', variant: 'default' },
    { title: 'JSON to JSONL Converter', variant: 'default' },
    { title: 'HTML to JSX Converter', variant: 'default' },
    { title: 'Markdown Table Generator', variant: 'default' },
    { title: 'Table to HTML Converter', variant: 'default' },
    { title: 'Scoreboard Online', variant: 'default' },
    { title: 'Latex Table Generator', variant: 'default' },
    { title: 'Cash App Fees Calculator', variant: 'default' },
    { title: 'Plaback Speed Calculator', variant: 'default' },
    { title: 'TOML to JSON Converter', variant: 'default' },
    { title: 'JSON to TOML Converter', variant: 'default' },
    { title: 'TOML Validator', variant: 'default' },
    { title: 'Saiyan Name Generator', variant: 'default' },
    { title: 'Roman Numeral Tattoo', variant: 'default' },
    { title: 'Random Coloring Pages', variant: 'default' },
    { title: 'Tiefling Name generator', variant: 'default' },
    { title: 'Dragonborn Name Generator', variant: 'default' },
    { title: 'Cultist Name Generator', variant: 'default' },
    { title: 'Wizard Name Generator', variant: 'default' },
    { title: 'Random Star War Characters', variant: 'default' },
    { title: 'Animal Fusion Generator', variant: 'default' },
    { title: 'Random Indiana Address', variant: 'default' },
    { title: 'Random Tongue Twister', variant: 'default' },
    { title: 'Random Texas Address', variant: 'default' },
    { title: 'JSON Sorter', variant: 'default' },
    { title: 'Small Text Generator', variant: 'default' },
    { title: 'Meme Generator', variant: 'default' },
    { title: 'Yes or No Generator', variant: 'default' },
    { title: 'Truth or Dare Generator', variant: 'default' },
    { title: 'Random Devil Fruit Generator', variant: 'default' },
    { title: 'Random Color Generator', variant: 'default' },
    { title: 'Random Sports Generator', variant: 'default' },
    { title: 'Random Restaurant Generator', variant: 'default' },
    { title: 'MultiLine to Single Line', variant: 'default' },
    { title: 'Random Candy Generator', variant: 'default' },
    { title: 'Random Disney Movie Generator', variant: 'default' },
    { title: 'Random DC Character Generator', variant: 'default' },
    { title: 'Marvel Character Generator', variant: 'default' },
    { title: 'Pitchch-Kincaid Grade Level', variant: 'default' },
    { title: 'Random Trivia Generator', variant: 'default' },
    { title: 'Random Website Generator', variant: 'default' },
    { title: 'Random Proverb Generator', variant: 'default' },
    { title: 'Memorable Password Generator', variant: 'default' },
    { title: 'Harry Potter Spells Generator', variant: 'default' },
    { title: 'Random New York Address', variant: 'default' },
    { title: 'Random Noun Generator', variant: 'default' },
    { title: 'Random Spanish Word Generator', variant: 'default' },
    { title: 'Random Location Generator', variant: 'default' },
    { title: 'Random Town Generator', variant: 'default' },
    { title: 'Goth Name Generator', variant: 'default' },
    { title: 'Fantasy Name Generator', variant: 'default' },
    { title: 'Victorian Name Generator', variant: 'default' },
    { title: 'Magic School Name', variant: 'default' },
    { title: 'Halloween Costume Generator', variant: 'default' },
    { title: 'Book Title Generator', variant: 'default' },
    { title: 'Disney Character Generator', variant: 'default' },
    { title: 'God Name Generator', variant: 'default' },
    { title: 'Random Setting Generator', variant: 'default' },
    { title: 'Twitch Name Generator', variant: 'default' },
    { title: 'Villager Name Generator', variant: 'default' },
    { title: 'Vampire Name Generator', variant: 'default' },
    { title: 'Dwarf Name Generator', variant: 'default' },
    { title: 'DND Name Generator', variant: 'default' },
    { title: 'Random Kingdom Name Generated', variant: 'default' },
    { title: 'Random Japanese Name Generator', variant: 'default' },
    { title: 'Random School Name Generator', variant: 'default' },
    { title: 'Glitch Text Generator', variant: 'default' },
    { title: 'YAML Cheat Sheet', variant: 'default' },
    { title: 'JSON Cheat Sheet', variant: 'default' },
    { title: 'Random Username Generator', variant: 'default' },
    { title: 'Random Cat Name Generator', variant: 'default' },
    { title: 'Random Food Generator', variant: 'default' },
    { title: 'Scenario Generator', variant: 'default' },
    { title: 'JSON to String', variant: 'default' },
    { title: 'Random New Zealand Address', variant: 'default' },
    { title: 'Random Paragraph Generator', variant: 'default' },
    { title: 'Fake ChatGPT Generator', variant: 'default' },
    { title: 'JavaScript Cheat Sheet', variant: 'default' },
    { title: 'Text Formatter', variant: 'default' },
    { title: 'Time Sheet Calculator', variant: 'default' },
    { title: 'Random Video Game Generator', variant: 'default' },
    { title: 'Address in Spain', variant: 'default' },
    { title: 'Random Actor Generator', variant: 'default' },
    { title: 'Random Song Lyrics', variant: 'default' },
    { title: 'Random Caption Generator', variant: 'default' },
    { title: 'Random Celebrity Generator', variant: 'default' },
    { title: 'Sort XML Online', variant: 'default' },
    { title: 'SVG Viewer', variant: 'default' },
    { title: 'SVG Formatter', variant: 'default' },
    { title: 'Cursed Text Generator', variant: 'default' },
    { title: 'Random Superhero Generator', variant: 'default' },
    { title: 'CSS Selectors Cheat Sheet', variant: 'default' },
    { title: 'HEX to RGBA Converter', variant: 'default' },
    { title: 'Sentence Counter', variant: 'default' },
    { title: 'JSON to One Line', variant: 'default' },
    { title: 'Paragraph Counter', variant: 'default' },
    { title: 'Javascript Tester', variant: 'default' },
    { title: 'Random Pokemon Team Generator', variant: 'default' },
    { title: 'Vim Cheat Sheet', variant: 'default' },
    { title: 'Random Canada Address Generator', variant: 'default' },
    { title: 'Random Pokemon Generator', variant: 'default' },
    { title: 'Random Address in California', variant: 'default' },
    { title: 'Random Movie Generator', variant: 'default' },
    { title: 'Character Trait Generator', variant: 'default' },
    { title: 'Random Flower Generator', variant: 'default' },
    { title: 'Random Quote Generator', variant: 'default' },
    { title: 'Random Sentence Generator', variant: 'default' },
    { title: 'Random Element Generator', variant: 'default' },
    { title: 'Random Planet Generator', variant: 'default' },
    { title: 'Random Holiday Generator', variant: 'default' },
    { title: 'Random Last Name Generator', variant: 'default' },
    { title: 'Random Cat Generator', variant: 'default' },
    { title: 'Random College Generator', variant: 'default' },
    { title: 'Random Bird Generator', variant: 'default' },
    { title: 'Random Book Generator', variant: 'default' },
    { title: 'Random Job Generator', variant: 'default' },
    { title: 'Random Link Generator', variant: 'default' },
    { title: 'Tweet to Image Converter', variant: 'default' },
    { title: 'PSN Name Generator', variant: 'default' },
    { title: 'Monster Generator', variant: 'default' },
    { title: 'Random League Champion', variant: 'default' },
    { title: 'Random Body Part Generator', variant: 'default' },
    { title: 'Social Tools', variant: 'default' },
    { title: 'Aesthetic Emoji Generator', variant: 'default' },
    { title: 'Random Superpower Generator', variant: 'default' },
    { title: 'Random Anime Character Generator', variant: 'default' },
    { title: 'Random Dinosaur Generator', variant: 'default' },
    { title: 'Fursona Generator', variant: 'default' },
    { title: 'Sims 3 Trait Generator', variant: 'default' },
    { title: 'Random Emotion Generator', variant: 'default' },
    { title: 'Random Year Generator', variant: 'default' },
    { title: 'Random Lorem Character Generator', variant: 'default' },
    { title: 'Random 6 Digit Number Generated', variant: 'default' },
    { title: 'Random 4 Digit Number Generated', variant: 'default' },
    { title: 'Random Birthday Generator', variant: 'default' },
    { title: 'Letter Randomizer', variant: 'default' },
    { title: 'Text Replacer', variant: 'default' },
    { title: 'Random Tarot Card Generator', variant: 'default' },
    { title: 'Random Dog Breed Generator', variant: 'default' },
    { title: 'Random Car Generator', variant: 'default' },
    { title: 'Lord Of The Rings Name Generator', variant: 'default' },
    { title: 'Fortune Cookie Generator', variant: 'default' },
    { title: 'Random Character Generator', variant: 'default' },
    { title: 'Instagram Caption Generator', variant: 'default' },
    { title: 'Snapchat Fonts Generator', variant: 'default' },
    { title: 'Reddit Username Generator', variant: 'default' },
    { title: 'Random Adjectives Generator', variant: 'default' },
    { title: 'Goofy Ahh Names Generator', variant: 'default' },
    { title: 'Random City Generator', variant: 'default' },
    { title: 'Personality Generator', variant: 'default' },
    { title: 'Random Girl Name Generator', variant: 'default' },
    { title: 'Random State Generator', variant: 'default' },
    { title: 'Full White Screen', variant: 'default' },
    { title: 'Full Blue Screen', variant: 'default' },
    { title: 'Full Red Screen', variant: 'default' },
    { title: 'Full Black Screen', variant: 'default' },
    { title: 'Aesthetic Username Generator', variant: 'default' },
    { title: 'Word Replacer', variant: 'default' },
    { title: 'Moodboard Generator', variant: 'default' },
    { title: 'Valorant Crosshair Generator', variant: 'default' },
    { title: 'Cookie Run Character Generator', variant: 'default' },
    { title: 'JoJo Stand Generator', variant: 'default' },
    { title: 'OTP Prompt Generator', variant: 'default' },
    { title: 'Random Minecraft Block Generator', variant: 'default' },
    { title: 'Random Theme Generator', variant: 'default' },
    { title: 'SQL Code Generator', variant: 'default' },
    { title: 'Random Pokemon Type Generator', variant: 'default' },
    { title: 'Fake Instagram Post Generator', variant: 'default' },
    { title: 'Random Aesthetic Generator', variant: 'default' },
    { title: 'Random Environment Generator', variant: 'default' },
    { title: 'Random Scene Generator', variant: 'default' },
    { title: 'XBOX GamerTag Generator', variant: 'default' },
    { title: 'Elf Name Generator', variant: 'default' },
    { title: 'Tatuaka Twitter Radios Generator', variant: 'default' },
    { title: 'XBOX Name Generator', variant: 'default' },
    { title: 'Warrior Cat Name Generator', variant: 'default' },
    { title: 'Fake Tweet Generator', variant: 'default' },
    { title: 'Random Topic Generator', variant: 'default' },
    { title: 'Pictionary Word Generator', variant: 'default' },
    { title: 'Random Things to Draw Generator', variant: 'default' },
    { title: 'Random Nationality Generator', variant: 'default' },
    { title: 'Random Ethnicity Generator', variant: 'default' },
    { title: 'Random Pet Generator', variant: 'default' },
    { title: 'Billing Postal Code Generator', variant: 'default' },
    { title: 'Random Male Name Generator', variant: 'default' },
    { title: 'Random Boy Name Generator', variant: 'default' },
    { title: 'Random Things Generator', variant: 'default' },
    { title: 'Random Milk Term Generator', variant: 'default' },
    { title: 'Random Zip Code', variant: 'default' },
    { title: 'Random Team Generator', variant: 'default' },
    { title: 'Random Billing Address', variant: 'default' },
    { title: 'Random House Address', variant: 'default' },
    { title: 'Random Street Address', variant: 'default' },
    { title: 'Random Address Generator', variant: 'default' },
    { title: 'Incorrect Quotes Generator', variant: 'default' },
    { title: 'Random Flag Generator', variant: 'default' },
    { title: 'Random Country Generator', variant: 'default' },
    { title: 'Random US Area Codes', variant: 'default' },
    { title: 'Random Phone Number', variant: 'default' },
    { title: 'React Formatter', variant: 'default' },
    { title: 'JSON Fixer', variant: 'default' },
    { title: 'JSON Navigator', variant: 'default' },
    { title: 'Random Emoji Generator', variant: 'default' },
    { title: 'Favicon Generator', variant: 'default' },
    { title: 'CIDR Calculator', variant: 'default' },
    { title: 'Marquee Generator', variant: 'default' },
    { title: 'Meta Tag Generator', variant: 'default' },
    { title: 'Screenshot Beautifier', variant: 'default' },
    { title: 'Tweet Ideas', variant: 'default' },
    { title: 'Number To WhatsApp', variant: 'default' },
    { title: 'Twitter Header Generator', variant: 'default' },
    { title: 'Twitter Image Downloader', variant: 'default' },
    { title: 'Random MLB Team Generator', variant: 'default' },
    { title: 'Random NBA Team Generator', variant: 'default' },
    { title: 'Random NCAA Football Team', variant: 'default' },
    { title: 'Random NCAA Basketball Team', variant: 'default' },
    { title: 'Random IPL Team Generator', variant: 'default' },
    { title: 'Random NFL Team Generator', variant: 'default' },
    { title: 'Random Object Generator', variant: 'default' },
    { title: 'Random Animal Generator', variant: 'default' },
    { title: 'Random Hobby Generator', variant: 'default' },
    { title: 'Code to Image Converter', variant: 'default' },
    { title: 'Multiple URL Opener', variant: 'default' },
    { title: 'Tweet Beautifier', variant: 'default' },
    { title: 'GIF Viewer', variant: 'default' },
    { title: 'GIF Splitter', variant: 'default' },
    { title: 'Share Code Snippets', variant: 'default' },
    { title: 'Convert Text to Handwriting', variant: 'default' },
    { title: 'Image Beautifier', variant: 'default' },
    { title: 'SVG to Base64', variant: 'default' },
    { title: 'Turbo Search', variant: 'default' },
    { title: 'Text Cleaner', variant: 'default' },
    { title: 'JSON Cleaner', variant: 'default' },
    { title: 'JSON to Typescript Code', variant: 'default' },
    { title: 'Online Vibration Simulator', variant: 'default' },
    { title: 'JSON to PHP Array Converter', variant: 'default' },
    { title: 'IELTS to CLB', variant: 'default' },
    { title: 'Hyperlink Generator', variant: 'default' },
    { title: 'REM to PX Converter', variant: 'default' },
    { title: 'Facebook Bold Text', variant: 'default' },
    { title: 'What is My Zodiac Sign', variant: 'default' },
    { title: 'Checksum Calculator', variant: 'default' },
    { title: 'SOAP Formatter', variant: 'default' },
    { title: 'WSDL Formatter', variant: 'default' },
    { title: 'Javascript Pretty Print', variant: 'default' },
    { title: 'Visualize JSON Data Graph', variant: 'default' },
    { title: 'Morse Code Translator', variant: 'default' },
    { title: 'Alphabetical Order', variant: 'default' },
    { title: 'Random AlphaNumenric Generator', variant: 'default' },
    { title: 'Hex to UTF8', variant: 'default' },
    { title: 'Byte to String', variant: 'default' },
    { title: 'UTF8 to ASCII', variant: 'default' },
    { title: 'Curl to PHP', variant: 'default' },
    { title: 'Phone Number to IP', variant: 'default' },
    { title: 'Yaml Parser', variant: 'default' },
    { title: 'XML Converter', variant: 'default' },
    { title: 'Gzip Decompress', variant: 'default' },
    { title: 'HTML Table Generator', variant: 'default' },
    { title: 'HTML Link Generator', variant: 'default' },
    { title: 'MP3 to Base64', variant: 'default' },
    { title: 'Base64 to Text', variant: 'default' },
    { title: 'Base64 to Ascii', variant: 'default' },
    { title: 'STYLUS Compiler', variant: 'default' },
    { title: 'JavaScript Obfuscator', variant: 'default' },
    { title: 'String to JSON Online', variant: 'default' },
    { title: 'YAML Pretty Print', variant: 'default' },
    { title: 'YouTube Thumbnail Grabber', variant: 'default' },
  ],
  trendingTools: [
    { title: 'Bitwise Calculator', variant: 'default' },
    { title: 'Number Sorter', variant: 'default' },
    { title: 'Remove Punctuation', variant: 'default' },
    { title: 'HTML Stripper', variant: 'default' },
    { title: 'Real Time HTML Editor', variant: 'default' },
    { title: 'HTML to Markdown', variant: 'default' },
    { title: 'Markdown to HTML', variant: 'default' },
    { title: 'Lua Minifier', variant: 'default' },
    { title: 'Lua Beautifier', variant: 'default' },
    { title: 'Wordpress Password Hash', variant: 'default' },
    { title: 'Mirror Online', variant: 'default' },
    { title: 'PHP Formatter', variant: 'default' },
    { title: 'Image to ASCII Art', variant: 'default' },
    { title: 'SHA256 Hash Generator', variant: 'default' },
    { title: 'SHA512 Hash Generator', variant: 'default' },
    { title: 'Excel Viewer', variant: 'default' },
    { title: 'Paraphrasing tool', variant: 'default' },
    { title: 'Word to HTML', variant: 'default' },
    { title: 'CSV to Excel', variant: 'default' },
    { title: 'Sharelink Generator', variant: 'default' },
  ],
  developmentTools: [
    { title: 'IP Tools', variant: 'default' },
    { title: 'Formatters & Beautifiers', variant: 'default' },
    { title: 'Image Converter Tools', variant: 'default' },
    { title: 'Finance Tools', variant: 'default' },
    { title: 'TSV Tools', variant: 'default' },
    { title: 'JSON Tools', variant: 'default' },
    { title: 'XML Tools', variant: 'default' },
    { title: 'YAML Tools', variant: 'default' },
    { title: 'HTML Tools', variant: 'default' },
    { title: 'CSS Tools', variant: 'default' },
    { title: 'Javascript Tools', variant: 'default' },
    { title: 'CSV Tools', variant: 'default' },
    { title: 'SQL Tools', variant: 'default' },
    { title: 'Color Tools', variant: 'default' },
    { title: 'Unit Tools', variant: 'default' },
    { title: 'Number Tools', variant: 'default' },
    { title: 'String Tools', variant: 'default' },
    { title: 'Base64 Tools', variant: 'default' },
    { title: 'Random Tools', variant: 'default' },
    { title: 'Minifiers', variant: 'default' },
    { title: 'Validators', variant: 'default' },
    { title: 'Cryptography', variant: 'default' },
    { title: 'Escape Unescape Tools', variant: 'default' },
    { title: 'UTF Tools', variant: 'default' },
    { title: 'Compress Decompress', variant: 'default' },
    { title: 'HTML Generators', variant: 'default' },
    { title: 'CSS Generators', variant: 'default' },
    { title: 'Other Tools', variant: 'default' },
    { title: 'Text Style Tools', variant: 'default' },
    { title: 'CSS Unit Converter Tools', variant: 'default' },
    { title: 'POJO Tools', variant: 'default' },
    { title: 'Twitter Tools', variant: 'default' },
    { title: 'Random Generators', variant: 'default' },
  ],
};
export const category = [

  {
    name: 'sql-converters', href: '/sql-converters',
    subcategories: [
      { name: 'SQL to CSV Converter', to: 'sql-converters/sql-to-csv' },
      { name: 'SQL to JSON Converter', to: 'sql-converters/sql-to-json' },
      { name: 'SQL to XML Converter', to: 'sql-converters/sql-to-xml' },
      { name: 'SQL to YAML Converter', to: 'sql-converters/sql-to-yaml' },
      { name: 'SQL to HTML Converter', to: 'sql-converters/sql-to-html' }
    ]
  },
  {
    name: 'encode-&-decode', href: '/encode-&-decode',
    subcategories: [
      { name: 'Base32 Encode', to: 'encode-&-decode/base32-encode' },
      { name: 'Base32 Decode', to: 'encode-&-decode/base32-decode' },
      { name: 'Base58 Encode', to: 'encode-&-decode/base58-encode' },
      { name: 'Base58 Decode', to: 'encode-&-decode/base58-decode' },
      { name: 'Base64 Encode', to: 'encode-&-decode/base64-encode' },
      { name: 'Base64 Decode', to: 'vbase64-decode' },
      { name: 'URL Encode Online', to: 'encode-&-decode/url-encode' },
      { name: 'URL Decode Online', to: 'encode-&-decode/url-decode' },
      { name: 'JSON URL Encode', to: 'encode-&-decode/json-url-encode' },
      { name: 'JSON URL Decode', to: 'encode-&-decode/json-url-decode' },
      { name: 'HTML Encode', to: 'encode-&-decode/html-encode' },
      { name: 'HTML Decode', to: 'encode-&-decode/html-decode' },
      { name: 'XML URL Encoding', to: 'encode-&-decode/xml-url-encode' },
      { name: 'XML URL Decoding', to: 'encode-&-decode/xml-url-decode' },
      { name: 'UTF8 Converter', to: 'encode-&-decode/utf8-converter' },
      { name: 'UTF8 Decode', to: 'encode-&-decode/utf8-decode' },
      { name: 'Hex to UTF8', to: 'encode-&-decode/hex-to-utf8' },
      { name: 'JSON Decode Online', to: 'encode-&-decode/json-decode' },
      { name: 'JSON Encode Online', to: 'encode-&-decode/json-encode' }
    ]
  },
  {
    name: 'base64-tools', href: '/base64-tools',
    subcategories: [
      { name: 'Image to Base64', to: 'base64-tools/image-to-base64' },
      { name: 'Base64 to Image', to: 'base64-tools/base64-to-image' },
      { name: 'PNG to Base64', to: 'base64-tools/png-to-base64' },
      { name: 'JPG to Base64', to: 'base64-tools/jpg-to-base64' },
      { name: 'JSON to Base64', to: 'base64-tools/json-to-base64' },
      { name: 'XML to Base64', to: 'base64-tools/xml-to-base64' },
      { name: 'YAML to Base64', to: 'base64-tools/yaml-to-base64' },
      { name: 'Base64 to JSON', to: 'base64-tools/base64-to-json' },
      { name: 'Base64 to XML', to: 'base64-tools/base64-to-xml' },
      { name: 'Base64 to YAML', to: 'base64-tools/base64-to-yaml' },
      { name: 'CSV to Base64', to: 'base64-tools/csv-to-base64' },
      { name: 'Base64 to CSV', to: 'base64-tools/base64-to-csv' },
      { name: 'TSV to Base64', to: 'base64-tools/tsv-to-base64' },
      { name: 'Base64 to TSV', to: 'base64-tools/base64-to-tsv' },
      { name: 'Binary to Base64', to: 'base64-tools/binary-to-base64' },
      { name: 'Base64 to Binary', to: 'base64-tools/base64-to-binary' },
      { name: 'Hex to Base64', to: 'base64-tools/hex-to-base64' },
      { name: 'Base64 to Hex', to: 'base64-tools/base64-to-hex' },
      { name: 'Octal to Base64', to: 'base64-tools/octal-to-base64' },
      { name: 'More Base64 Tools', to: 'base64-tools/more-base64-tools' }
    ]
  },
  {
    name: 'image-tools', href: '/image-tools',
    subcategories: [
      { name: 'JPG to PNG', to: 'image-tools/jpg-to-png' },
      { name: 'BMP to PNG', to: 'image-tools/bmp-to-png' },
      { name: 'PNG to JPG', to: 'image-tools/png-to-jpg' },
      { name: 'GIF Splitter', to: 'image-tools/gif-splitter' },
      { name: 'GIF Viewer', to: 'image-tools/gif-viewer' },
      { name: 'More Image Tools', to: 'image-tools/more-image-tools' }
    ]
  },

  {
    name: 'json-converters', href: '/json-converters',
    subcategories: [
      { name: 'JSON to JAVA', to: 'json-converters/json-to-java' },
      { name: 'JSON to XML', to: 'json-converters/json-to-xml' },
      { name: 'JSON to YAML', to: 'json-converters/json-to-yaml' },
      { name: 'JSON to CSV', to: 'json-converters/json-to-csv' },
      { name: 'JSON to TSV', to: 'json-converters/json-to-tsv' },
      { name: 'JSON to Text', to: 'json-converters/json-to-text' },
      { name: 'JSON to Excel', to: 'json-converters/json-to-excel' },
      { name: 'JSON to HTML', to: 'json-converters/json-to-html' }
    ]
  },
  {
    name: 'XML Converters', href: '/xml-converters',
    subcategories: [
      { name: 'XML Converter', to: 'XML-Converters/xml-converter' },
      { name: 'XML to JSON', to: 'XML-Converters/xml-to-json' },
      { name: 'XML to YAML', to: 'XML-Converters/xml-to-yaml' },
      { name: 'XML to CSV', to: 'XML-Converters/xml-to-csv' },
      { name: 'XML to TSV', to: 'XML-Converters/xml-to-tsv' },
      { name: 'XML to Text', to: 'XML-Converters/xml-to-text' },
      { name: 'XML-XSL Transform', to: 'XML-Converters/xml-xsl-transform' },
      { name: 'XML to HTML', to: 'XML-Converters/xml-to-html' },
      { name: 'XML to Excel', to: 'XML-Converters/xml-to-excel' },
      { name: 'XML to JAVA', to: 'XML-Converters/xml-to-java' }
    ]
  },
  {
    name: 'HTML Converters', href: '/html-converters',
    subcategories: [
      { name: 'HTML Stripper', to: 'html-stripper' },
      { name: 'HTML Table Generator', to: 'HTML-Converters/html-table-generator' },
      { name: 'HTML to CSV Converter', to: 'HTML-Converters/html-to-csv-converter' },
      { name: 'HTML to TSV Converter', to: 'HTML-Converters/html-to-tsv-converter' },
      { name: 'HTML to PHP Converter', to: 'HTML-Converters/html-to-php-converter' },
      { name: 'HTML to CSV', to: 'HTML-Converters/html-to-csv' },
      { name: 'HTML to JSON', to: 'HTML-Converters/html-to-json' },
      { name: 'HTML to XML', to: 'HTML-Converters/html-to-xml' },
      { name: 'HTML to YAML', to: 'HTML-Converters/html-to-yaml' },
      { name: 'HTML to Text', to: 'HTML-Converters/html-to-text' },
      { name: 'Text to HTML Entities', to: 'HTML-Converters/text-to-html-entities' },
      { name: 'HTML Entities to Text', to: 'HTML-Converters/html-entities-to-text' },
      { name: 'HTML to Markdown', to: 'HTML-Converters/html-to-markdown' },
      { name: 'Markdown to HTML', to: 'HTML-Converters/markdown-to-html' },
      { name: 'PUG to HTML Converter', to: 'HTML-Converters/pug-to-html-converter' },
      { name: 'HTML to PUG Converter', to: 'HTML-Converters/html-to-pug-converter' },
      { name: 'JADE to HTML Converter', to: 'HTML-Converters/jade-to-html-converter' },
      { name: 'HTML to JADE Converter', to: 'HTML-Converters/html-to-jade-converter' },
      { name: 'HTML to BBCode Converter', to: 'HTML-Converters/html-to-bbcode-converter' },
      { name: 'BBCode to HTML Converter', to: 'HTML-Converters/bbcode-to-html-converter' }
    ]
  },
  {
    name: 'yaml-converters', href: '/yaml-converters',
    subcategories: [
      { name: 'YAML Converter', to: 'yaml-converters/yaml-converter' },
      { name: 'YAML to JSON', to: 'yaml-converters/yaml-to-json' },
      { name: 'YAML to XML', to: 'yaml-converters/yaml-to-xml' },
      { name: 'YAML to CSV', to: 'yaml-converters/yaml-to-csv' },
      { name: 'YAML to TSV', to: 'yaml-converters/yaml-to-tsv' },
      { name: 'YAML to TEXT', to: 'yaml-converters/yaml-to-text' },
      { name: 'YAML to HTML', to: 'yaml-converters/yaml-to-html' },
    ]
  },
  {
    name: 'utility', href: '/utility',
    subcategories: [
      { name: 'Send Snap Message', to: 'Utility/send-snap-message' },
      { name: 'Responsive Website Tester', to: 'Utility/responsive-website-tester' },
      { name: 'Credit Card Validator', to: 'Utility/credit-card-validator' },
      { name: 'Credit Card Fake Number Generator', to: 'Utility/credit-card-fake-number-generator' },
      { name: 'XPath Tester', to: 'Utility/xpath-tester' },
      { name: 'JSON Path Tester', to: 'Utility/json-path-tester' },
      { name: 'JSON Minifier', to: 'Utility/json-minifier' },
      { name: 'File Difference', to: 'Utility/file-difference' },
      { name: 'JSON Diff', to: 'Utility/json-diff' },
      { name: 'XML Diff', to: 'Utility/xml-diff' },
      { name: 'Broken Link Checker', to: 'Utility/broken-link-checker' },
      { name: 'JSON Deserialize Online', to: 'Utility/json-deserialize-online' },
      { name: 'JSON Serialize Online', to: 'Utility/json-serialize-online' },
      { name: 'JSON Stringify Online', to: 'Utility/json-stringify-online' },
      { name: 'XML Stringify Online', to: 'Utility/xml-stringify-online' },
      { name: 'String to JSON Online', to: 'Utility/string-to-json-online' },
      { name: 'JavaScript Obfuscator', to: 'Utility/javascript-obfuscator' },
      { name: 'Curl to PHP', to: 'Utility/curl-to-php' },
      { name: 'Crontab Format', to: 'Utility/crontab-format' }
    ]
  },
];
export const categories = [
  { id: 'popular', name: 'Popular Tools', icon: "TrendingUp" },
  { id: 'navbar', name: 'Navbar', icon: "SiNaver" },
  { id: 'trendingtools', name: 'Trending Tools', icon: "Sparkles" },
  { id: 'encode_decode', name: 'Encode / Decode', icon: "Shield" },
  { id: 'base64_tools', name: 'Base64 Tools', icon: "Layers" },
  { id: 'html_converters', name: 'HTML Converters', icon: "FileText" },
  { id: 'json_converters', name: 'JSON Converters', icon: "Braces" },
  { id: 'xml_converters', name: 'XML Converters', icon: "FileText" },
  { id: 'yaml_converters', name: 'YAML Converters', icon: "FileText" },
  { id: 'sql_converters', name: 'SQL Converters', icon: "Database" },
  { id: 'image_tools', name: 'Image Tools', icon: "Image" },
  { id: 'nf', name: 'New Features', icon: "Sparkles" },
  { id: 'pdf', name: 'PDF Tools', icon: "PDF" },
];
export const GUIDES = {
  'web-to-pdf-guide': {
    title: 'How to Save a Web Page as PDF',
    steps: [
      {
        t: 'Chrome / Edge / Firefox',
        d: 'Press Ctrl+P (Cmd+P on Mac) → Set Destination to "Save as PDF" → Click Save.',
      },
      { t: 'Safari on Mac', d: 'File menu → Export as PDF → Choose location and save.' },
      { t: 'iPhone / iPad', d: 'Share button → Options → PDF → Save to Files.' },
      { t: 'Android Chrome', d: 'Three-dot menu → Share → Print → Save as PDF.' },
      {
        t: 'Using HTML to PDF tool above',
        d: 'Save the webpage as HTML file (Ctrl+S), then upload the HTML file here.',
      },
    ],
  },
  'sign-guide': {
    title: 'How to Electronically Sign a PDF',
    steps: [
      {
        t: 'Use our Sign PDF tool',
        d: 'Upload PDF → Draw your signature in the canvas → Click Apply → Download signed PDF.',
      },
      {
        t: 'Adobe Acrobat Reader (Free)',
        d: 'Open PDF → Fill & Sign → Draw or type signature → Position it → Save.',
      },
      {
        t: 'Preview on Mac',
        d: 'Open in Preview → Markup toolbar → Signature → Create → Drag onto document.',
      },
      { t: 'Microsoft Edge', d: 'Open PDF in Edge → Draw tool → Sign → Save a copy.' },
      {
        t: 'Online: DocuSign / HelloSign',
        d: 'These services provide legally binding electronic signatures.',
      },
    ],
  },
  'split-guide': {
    title: 'How to Split PDF Pages',
    steps: [
      {
        t: 'Use our Split PDF tool',
        d: 'Upload PDF → Enter ranges like "1-3, 4-6" → Each range downloads as a PDF.',
      },
      { t: 'Extract a single page', d: 'Enter just "3" to extract only page 3 as its own PDF.' },
      { t: 'Split every page', d: 'Leave range blank — splits every page into individual PDFs.' },
      { t: 'Adobe Acrobat (paid)', d: 'Tools → Organize Pages → Split → set pages per file.' },
    ],
  },
  'fill-guide': {
    title: 'How to Fill Out a PDF Form',
    steps: [
      {
        t: 'Use our Fill PDF Form tool',
        d: 'Upload PDF → Click "Load Form Fields" → Fill in values → Download.',
      },
      {
        t: 'Adobe Acrobat Reader (Free)',
        d: 'Open PDF → form fields are clickable — type, check boxes, sign. Save.',
      },
      { t: 'Chrome Browser', d: 'Open PDF in Chrome → click on form fields and type directly.' },
      {
        t: 'Preview on Mac',
        d: 'Open PDF → form fields auto-detected → click and fill → Export as PDF.',
      },
      {
        t: 'Non-fillable PDF?',
        d: 'Use our Edit PDF tool to add text boxes over the field areas manually.',
      },
    ],
  },
  'excel-tips': {
    title: 'Excel Tips & Tricks',
    steps: [
      {
        t: 'Add a tick/checkmark (✓)',
        d: 'Method 1: In a cell type =CHAR(252) and set font to Wingdings. Method 2: Insert → Symbol → Wingdings font → select ✓.',
      },
      {
        t: 'Number pages in Excel',
        d: 'Insert → Header & Footer → click footer section → Insert Page Number. Format: &[Page] of &[Pages].',
      },
      {
        t: 'Un-concatenate / split text',
        d: 'Use Data → Text to Columns. Or formulas: =LEFT(A1,3), =RIGHT(A1,3), =MID(A1,2,4).',
      },
      {
        t: 'Check duplicates in Excel',
        d: 'Home → Conditional Formatting → Highlight Cell Rules → Duplicate Values. Or use our Duplicate Checker tool.',
      },
      {
        t: 'Remove blank lines',
        d: 'Ctrl+G → Special → Blanks → Right-click → Delete Entire Row. Or use our Remove Blank Rows tool.',
      },
      {
        t: 'How to accept edits in Word',
        d: 'Review tab → Accept → Accept All Changes. Or right-click a tracked change → Accept.',
      },
      {
        t: 'Remove page corners/borders in Word',
        d: 'Design tab → Page Borders → None → OK. For text box borders: right-click → Format Shape → No line.',
      },
    ],
  },
  'pdf-to-ppt': {
    title: 'PDF to PowerPoint',
    steps: [
      {
        t: 'Step 1: Convert PDF pages to images',
        d: 'Use our "PDF to JPG" tool to download each page as a JPG image.',
      },
      { t: 'Step 2: Create new PowerPoint', d: 'Open PowerPoint → New blank presentation.' },
      {
        t: 'Step 3: Insert images as slides',
        d: 'For each slide: Insert → Pictures → select the page JPG → resize to fill slide.',
      },
      {
        t: 'Online tools',
        d: 'SmallPDF.com, ILovePDF.com, and Adobe Acrobat (paid) can convert PDF to PPTX directly.',
      },
      {
        t: 'LibreOffice Impress (Free)',
        d: 'Open LibreOffice Impress → Insert → Image for each PDF page image.',
      },
    ],
  },
};