export const constants = {
  tools: [
    { title: 'JSON Beautifier', variant: 'default' },
    { title: 'HTML Viewer', variant: 'default' },
    { title: 'Number to Words', variant: 'default' },
    { title: 'SQL Formatter', variant: 'default' },
    { title: 'Image to Base64', variant: 'default' },
    { title: 'Base64 to Image', variant: 'default' },
    { title: 'HEX to Pantone', variant: 'default' },
    { title: 'Source Code Viewer', variant: 'default' },
    { title: 'Binary to Text', variant: 'default' },
    { title: 'JSON Viewer', variant: 'default' },
    { title: 'JSON Validator', variant: 'default' },
    { title: 'Base64 Decode', variant: 'default' },
    { title: 'Hex to Decimal', variant: 'default' },
    { title: 'XML Viewer', variant: 'default' },
    { title: 'XML to JSON', variant: 'default' },
    { title: 'Encryption-Decryption', variant: 'default' },
    { title: 'Excel to HTML', variant: 'default' },
    { title: 'CSS Validator', variant: 'default' },
    { title: 'XML Validator', variant: 'default' },
    { title: 'JavaScript Validator', variant: 'default' },
    { title: 'CSS Beautifier', variant: 'primary' },
    { title: 'ONLINE JSON EDITOR', variant: 'default' },
    { title: 'Decimal to Hex', variant: 'default' },
    { title: 'Binary to Decimal', variant: 'default' },
    { title: 'ASCII to Text', variant: 'default' },
    { title: 'Random Emoji Generator', variant: 'default' },
    { title: 'REM to PX Converter', variant: 'default' },
    { title: 'Incorrect Quotes Generator', variant: 'default' },
    { title: 'Lua Beautifier', variant: 'default' },
  ],
  newFundata: [
    { title: 'Flag Maker', variant: 'default' },
    { title: 'Code to ASCII', variant: 'default' },
    { title: 'Inches to Pixels', variant: 'default' },
    { title: 'Vertical Font Generator', variant: 'default' },
    { title: 'JSON MultiLine String', variant: 'default' },
    { title: 'JWT Decode', variant: 'default' },
    { title: 'JSON to JSONL Converter', variant: 'default' },
    { title: 'HTML to JSX Converter', variant: 'default' },
    { title: 'Markdown Table Generator', variant: 'default' },
    { title: 'Table to HTML Converter', variant: 'default' },
    { title: 'Scoreboard Online', variant: 'default' },
    { title: 'Latex Table Generator', variant: 'default' },
    { title: 'Cash App Fees Calculator', variant: 'default' },
    { title: 'Plaback Speed Calculator', variant: 'default' },
    { title: 'TOML to JSON Converter', variant: 'default' },
    { title: 'JSON to TOML Converter', variant: 'default' },
    { title: 'TOML Validator', variant: 'default' },
    { title: 'Saiyan Name Generator', variant: 'default' },
    { title: 'Roman Numeral Tattoo', variant: 'default' },
    { title: 'Random Coloring Pages', variant: 'default' },
    { title: 'Tiefling Name generator', variant: 'default' },
    { title: 'Dragonborn Name Generator', variant: 'default' },
    { title: 'Cultist Name Generator', variant: 'default' },
    { title: 'Wizard Name Generator', variant: 'default' },
    { title: 'Random Star War Characters', variant: 'default' },
    { title: 'Animal Fusion Generator', variant: 'default' },
    { title: 'Random Indiana Address', variant: 'default' },
    { title: 'Random Tongue Twister', variant: 'default' },
    { title: 'Random Texas Address', variant: 'default' },
    { title: 'JSON Sorter', variant: 'default' },
    { title: 'Small Text Generator', variant: 'default' },
    { title: 'Meme Generator', variant: 'default' },
    { title: 'Yes or No Generator', variant: 'default' },
    { title: 'Truth or Dare Generator', variant: 'default' },
    { title: 'Random Devil Fruit Generator', variant: 'default' },
    { title: 'Random Color Generator', variant: 'default' },
    { title: 'Random Sports Generator', variant: 'default' },
    { title: 'Random Restaurant Generator', variant: 'default' },
    { title: 'MultiLine to Single Line', variant: 'default' },
    { title: 'Random Candy Generator', variant: 'default' },
    { title: 'Random Disney Movie Generator', variant: 'default' },
    { title: 'Random DC Character Generator', variant: 'default' },
    { title: 'Marvel Character Generator', variant: 'default' },
    { title: 'Pitchch-Kincaid Grade Level', variant: 'default' },
    { title: 'Random Trivia Generator', variant: 'default' },
    { title: 'Random Website Generator', variant: 'default' },
    { title: 'Random Proverb Generator', variant: 'default' },
    { title: 'Memorable Password Generator', variant: 'default' },
    { title: 'Harry Potter Spells Generator', variant: 'default' },
    { title: 'Random New York Address', variant: 'default' },
    { title: 'Random Noun Generator', variant: 'default' },
    { title: 'Random Spanish Word Generator', variant: 'default' },
    { title: 'Random Location Generator', variant: 'default' },
    { title: 'Random Town Generator', variant: 'default' },
    { title: 'Goth Name Generator', variant: 'default' },
    { title: 'Fantasy Name Generator', variant: 'default' },
    { title: 'Victorian Name Generator', variant: 'default' },
    { title: 'Magic School Name', variant: 'default' },
    { title: 'Halloween Costume Generator', variant: 'default' },
    { title: 'Book Title Generator', variant: 'default' },
    { title: 'Disney Character Generator', variant: 'default' },
    { title: 'God Name Generator', variant: 'default' },
    { title: 'Random Setting Generator', variant: 'default' },
    { title: 'Twitch Name Generator', variant: 'default' },
    { title: 'Villager Name Generator', variant: 'default' },
    { title: 'Vampire Name Generator', variant: 'default' },
    { title: 'Dwarf Name Generator', variant: 'default' },
    { title: 'DND Name Generator', variant: 'default' },
    { title: 'Random Kingdom Name Generated', variant: 'default' },
    { title: 'Random Japanese Name Generator', variant: 'default' },
    { title: 'Random School Name Generator', variant: 'default' },
    { title: 'Glitch Text Generator', variant: 'default' },
    { title: 'YAML Cheat Sheet', variant: 'default' },
    { title: 'JSON Cheat Sheet', variant: 'default' },
    { title: 'Random Username Generator', variant: 'default' },
    { title: 'Random Cat Name Generator', variant: 'default' },
    { title: 'Random Food Generator', variant: 'default' },
    { title: 'Scenario Generator', variant: 'default' },
    { title: 'JSON to String', variant: 'default' },
    { title: 'Random New Zealand Address', variant: 'default' },
    { title: 'Random Paragraph Generator', variant: 'default' },
    { title: 'Fake ChatGPT Generator', variant: 'default' },
    { title: 'JavaScript Cheat Sheet', variant: 'default' },
    { title: 'Text Formatter', variant: 'default' },
    { title: 'Time Sheet Calculator', variant: 'default' },
    { title: 'Random Video Game Generator', variant: 'default' },
    { title: 'Address in Spain', variant: 'default' },
    { title: 'Random Actor Generator', variant: 'default' },
    { title: 'Random Song Lyrics', variant: 'default' },
    { title: 'Random Caption Generator', variant: 'default' },
    { title: 'Random Celebrity Generator', variant: 'default' },
    { title: 'Sort XML Online', variant: 'default' },
    { title: 'SVG Viewer', variant: 'default' },
    { title: 'SVG Formatter', variant: 'default' },
    { title: 'Cursed Text Generator', variant: 'default' },
    { title: 'Random Superhero Generator', variant: 'default' },
    { title: 'CSS Selectors Cheat Sheet', variant: 'default' },
    { title: 'HEX to RGBA Converter', variant: 'default' },
    { title: 'Sentence Counter', variant: 'default' },
    { title: 'JSON to One Line', variant: 'default' },
    { title: 'Paragraph Counter', variant: 'default' },
    { title: 'Javascript Tester', variant: 'default' },
    { title: 'Random Pokemon Team Generator', variant: 'default' },
    { title: 'Vim Cheat Sheet', variant: 'default' },
    { title: 'Random Canada Address Generator', variant: 'default' },
    { title: 'Random Pokemon Generator', variant: 'default' },
    { title: 'Random Address in California', variant: 'default' },
    { title: 'Random Movie Generator', variant: 'default' },
    { title: 'Character Trait Generator', variant: 'default' },
    { title: 'Random Flower Generator', variant: 'default' },
    { title: 'Random Quote Generator', variant: 'default' },
    { title: 'Random Sentence Generator', variant: 'default' },
    { title: 'Random Element Generator', variant: 'default' },
    { title: 'Random Planet Generator', variant: 'default' },
    { title: 'Random Holiday Generator', variant: 'default' },
    { title: 'Random Last Name Generator', variant: 'default' },
    { title: 'Random Cat Generator', variant: 'default' },
    { title: 'Random College Generator', variant: 'default' },
    { title: 'Random Bird Generator', variant: 'default' },
    { title: 'Random Book Generator', variant: 'default' },
    { title: 'Random Job Generator', variant: 'default' },
    { title: 'Random Link Generator', variant: 'default' },
    { title: 'Tweet to Image Converter', variant: 'default' },
    { title: 'PSN Name Generator', variant: 'default' },
    { title: 'Monster Generator', variant: 'default' },
    { title: 'Random League Champion', variant: 'default' },
    { title: 'Random Body Part Generator', variant: 'default' },
    { title: 'Social Tools', variant: 'default' },
    { title: 'Aesthetic Emoji Generator', variant: 'default' },
    { title: 'Random Superpower Generator', variant: 'default' },
    { title: 'Random Anime Character Generator', variant: 'default' },
    { title: 'Random Dinosaur Generator', variant: 'default' },
    { title: 'Fursona Generator', variant: 'default' },
    { title: 'Sims 3 Trait Generator', variant: 'default' },
    { title: 'Random Emotion Generator', variant: 'default' },
    { title: 'Random Year Generator', variant: 'default' },
    { title: 'Random Lorem Character Generator', variant: 'default' },
    { title: 'Random 6 Digit Number Generated', variant: 'default' },
    { title: 'Random 4 Digit Number Generated', variant: 'default' },
    { title: 'Random Birthday Generator', variant: 'default' },
    { title: 'Letter Randomizer', variant: 'default' },
    { title: 'Text Replacer', variant: 'default' },
    { title: 'Random Tarot Card Generator', variant: 'default' },
    { title: 'Random Dog Breed Generator', variant: 'default' },
    { title: 'Random Car Generator', variant: 'default' },
    { title: 'Lord Of The Rings Name Generator', variant: 'default' },
    { title: 'Fortune Cookie Generator', variant: 'default' },
    { title: 'Random Character Generator', variant: 'default' },
    { title: 'Instagram Caption Generator', variant: 'default' },
    { title: 'Snapchat Fonts Generator', variant: 'default' },
    { title: 'Reddit Username Generator', variant: 'default' },
    { title: 'Random Adjectives Generator', variant: 'default' },
    { title: 'Goofy Ahh Names Generator', variant: 'default' },
    { title: 'Random City Generator', variant: 'default' },
    { title: 'Personality Generator', variant: 'default' },
    { title: 'Random Girl Name Generator', variant: 'default' },
    { title: 'Random State Generator', variant: 'default' },
    { title: 'Full White Screen', variant: 'default' },
    { title: 'Full Blue Screen', variant: 'default' },
    { title: 'Full Red Screen', variant: 'default' },
    { title: 'Full Black Screen', variant: 'default' },
    { title: 'Aesthetic Username Generator', variant: 'default' },
    { title: 'Word Replacer', variant: 'default' },
    { title: 'Moodboard Generator', variant: 'default' },
    { title: 'Valorant Crosshair Generator', variant: 'default' },
    { title: 'Cookie Run Character Generator', variant: 'default' },
    { title: 'JoJo Stand Generator', variant: 'default' },
    { title: 'OTP Prompt Generator', variant: 'default' },
    { title: 'Random Minecraft Block Generator', variant: 'default' },
    { title: 'Random Theme Generator', variant: 'default' },
    { title: 'SQL Code Generator', variant: 'default' },
    { title: 'Random Pokemon Type Generator', variant: 'default' },
    { title: 'Fake Instagram Post Generator', variant: 'default' },
    { title: 'Random Aesthetic Generator', variant: 'default' },
    { title: 'Random Environment Generator', variant: 'default' },
    { title: 'Random Scene Generator', variant: 'default' },
    { title: 'XBOX GamerTag Generator', variant: 'default' },
    { title: 'Elf Name Generator', variant: 'default' },
    { title: 'Tatuaka Twitter Radios Generator', variant: 'default' },
    { title: 'XBOX Name Generator', variant: 'default' },
    { title: 'Warrior Cat Name Generator', variant: 'default' },
    { title: 'Fake Tweet Generator', variant: 'default' },
    { title: 'Random Topic Generator', variant: 'default' },
    { title: 'Pictionary Word Generator', variant: 'default' },
    { title: 'Random Things to Draw Generator', variant: 'default' },
    { title: 'Random Nationality Generator', variant: 'default' },
    { title: 'Random Ethnicity Generator', variant: 'default' },
    { title: 'Random Pet Generator', variant: 'default' },
    { title: 'Billing Postal Code Generator', variant: 'default' },
    { title: 'Random Male Name Generator', variant: 'default' },
    { title: 'Random Boy Name Generator', variant: 'default' },
    { title: 'Random Things Generator', variant: 'default' },
    { title: 'Random Milk Term Generator', variant: 'default' },
    { title: 'Random Zip Code', variant: 'default' },
    { title: 'Random Team Generator', variant: 'default' },
    { title: 'Random Billing Address', variant: 'default' },
    { title: 'Random House Address', variant: 'default' },
    { title: 'Random Street Address', variant: 'default' },
    { title: 'Random Address Generator', variant: 'default' },
    { title: 'Incorrect Quotes Generator', variant: 'default' },
    { title: 'Random Flag Generator', variant: 'default' },
    { title: 'Random Country Generator', variant: 'default' },
    { title: 'Random US Area Codes', variant: 'default' },
    { title: 'Random Phone Number', variant: 'default' },
    { title: 'React Formatter', variant: 'default' },
    { title: 'JSON Fixer', variant: 'default' },
    { title: 'JSON Navigator', variant: 'default' },
    { title: 'Random Emoji Generator', variant: 'default' },
    { title: 'Favicon Generator', variant: 'default' },
    { title: 'CIDR Calculator', variant: 'default' },
    { title: 'Marquee Generator', variant: 'default' },
    { title: 'Meta Tag Generator', variant: 'default' },
    { title: 'Screenshot Beautifier', variant: 'default' },
    { title: 'Tweet Ideas', variant: 'default' },
    { title: 'Number To WhatsApp', variant: 'default' },
    { title: 'Twitter Header Generator', variant: 'default' },
    { title: 'Twitter Image Downloader', variant: 'default' },
    { title: 'Random MLB Team Generator', variant: 'default' },
    { title: 'Random NBA Team Generator', variant: 'default' },
    { title: 'Random NCAA Football Team', variant: 'default' },
    { title: 'Random NCAA Basketball Team', variant: 'default' },
    { title: 'Random IPL Team Generator', variant: 'default' },
    { title: 'Random NFL Team Generator', variant: 'default' },
    { title: 'Random Object Generator', variant: 'default' },
    { title: 'Random Animal Generator', variant: 'default' },
    { title: 'Random Hobby Generator', variant: 'default' },
    { title: 'Code to Image Converter', variant: 'default' },
    { title: 'Multiple URL Opener', variant: 'default' },
    { title: 'Tweet Beautifier', variant: 'default' },
    { title: 'GIF Viewer', variant: 'default' },
    { title: 'GIF Splitter', variant: 'default' },
    { title: 'Share Code Snippets', variant: 'default' },
    { title: 'Convert Text to Handwriting', variant: 'default' },
    { title: 'Image Beautifier', variant: 'default' },
    { title: 'SVG to Base64', variant: 'default' },
    { title: 'Turbo Search', variant: 'default' },
    { title: 'Text Cleaner', variant: 'default' },
    { title: 'JSON Cleaner', variant: 'default' },
    { title: 'JSON to Typescript Code', variant: 'default' },
    { title: 'Online Vibration Simulator', variant: 'default' },
    { title: 'JSON to PHP Array Converter', variant: 'default' },
    { title: 'IELTS to CLB', variant: 'default' },
    { title: 'Hyperlink Generator', variant: 'default' },
    { title: 'REM to PX Converter', variant: 'default' },
    { title: 'Facebook Bold Text', variant: 'default' },
    { title: 'What is My Zodiac Sign', variant: 'default' },
    { title: 'Checksum Calculator', variant: 'default' },
    { title: 'SOAP Formatter', variant: 'default' },
    { title: 'WSDL Formatter', variant: 'default' },
    { title: 'Javascript Pretty Print', variant: 'default' },
    { title: 'Visualize JSON Data Graph', variant: 'default' },
    { title: 'Morse Code Translator', variant: 'default' },
    { title: 'Alphabetical Order', variant: 'default' },
    { title: 'Random AlphaNumenric Generator', variant: 'default' },
    { title: 'Hex to UTF8', variant: 'default' },
    { title: 'Byte to String', variant: 'default' },
    { title: 'UTF8 to ASCII', variant: 'default' },
    { title: 'Curl to PHP', variant: 'default' },
    { title: 'Phone Number to IP', variant: 'default' },
    { title: 'Yaml Parser', variant: 'default' },
    { title: 'XML Converter', variant: 'default' },
    { title: 'Gzip Decompress', variant: 'default' },
    { title: 'HTML Table Generator', variant: 'default' },
    { title: 'HTML Link Generator', variant: 'default' },
    { title: 'MP3 to Base64', variant: 'default' },
    { title: 'Base64 to Text', variant: 'default' },
    { title: 'Base64 to Ascii', variant: 'default' },
    { title: 'STYLUS Compiler', variant: 'default' },
    { title: 'JavaScript Obfuscator', variant: 'default' },
    { title: 'String to JSON Online', variant: 'default' },
    { title: 'YAML Pretty Print', variant: 'default' },
    { title: 'YouTube Thumbnail Grabber', variant: 'default' },
  ],
  trendingTools: [
    { title: 'Bitwise Calculator', variant: 'default' },
    { title: 'Number Sorter', variant: 'default' },
    { title: 'Remove Punctuation', variant: 'default' },
    { title: 'HTML Stripper', variant: 'default' },
    { title: 'Real Time HTML Editor', variant: 'default' },
    { title: 'HTML to Markdown', variant: 'default' },
    { title: 'Markdown to HTML', variant: 'default' },
    { title: 'Lua Minifier', variant: 'default' },
    { title: 'Lua Beautifier', variant: 'default' },
    { title: 'Wordpress Password Hash', variant: 'default' },
    { title: 'Mirror Online', variant: 'default' },
    { title: 'PHP Formatter', variant: 'default' },
    { title: 'Image to ASCII Art', variant: 'default' },
    { title: 'SHA256 Hash Generator', variant: 'default' },
    { title: 'SHA512 Hash Generator', variant: 'default' },
    { title: 'Excel Viewer', variant: 'default' },
    { title: 'Paraphrasing tool', variant: 'default' },
    { title: 'Word to HTML', variant: 'default' },
    { title: 'CSV to Excel', variant: 'default' },
    { title: 'Sharelink Generator', variant: 'default' },
  ],
  developmentTools: [
    { title: 'IP Tools', variant: 'default' },
    { title: 'Formatters & Beautifiers', variant: 'default' },
    { title: 'Image Converter Tools', variant: 'default' },
    { title: 'Finance Tools', variant: 'default' },
    { title: 'TSV Tools', variant: 'default' },
    { title: 'JSON Tools', variant: 'default' },
    { title: 'XML Tools', variant: 'default' },
    { title: 'YAML Tools', variant: 'default' },
    { title: 'HTML Tools', variant: 'default' },
    { title: 'CSS Tools', variant: 'default' },
    { title: 'Javascript Tools', variant: 'default' },
    { title: 'CSV Tools', variant: 'default' },
    { title: 'SQL Tools', variant: 'default' },
    { title: 'Color Tools', variant: 'default' },
    { title: 'Unit Tools', variant: 'default' },
    { title: 'Number Tools', variant: 'default' },
    { title: 'String Tools', variant: 'default' },
    { title: 'Base64 Tools', variant: 'default' },
    { title: 'Random Tools', variant: 'default' },
    { title: 'Minifiers', variant: 'default' },
    { title: 'Validators', variant: 'default' },
    { title: 'Cryptography', variant: 'default' },
    { title: 'Escape Unescape Tools', variant: 'default' },
    { title: 'UTF Tools', variant: 'default' },
    { title: 'Compress Decompress', variant: 'default' },
    { title: 'HTML Generators', variant: 'default' },
    { title: 'CSS Generators', variant: 'default' },
    { title: 'Other Tools', variant: 'default' },
    { title: 'Text Style Tools', variant: 'default' },
    { title: 'CSS Unit Converter Tools', variant: 'default' },
    { title: 'POJO Tools', variant: 'default' },
    { title: 'Twitter Tools', variant: 'default' },
    { title: 'Random Generators', variant: 'default' },
  ],
};
export const category = [

  {
    name: 'sql-converters', href: '/sql-converters',
    subcategories: [
      { name: 'SQL to CSV Converter', to: 'sql-converters/sql-to-csv' },
      { name: 'SQL to JSON Converter', to: 'sql-converters/sql-to-json' },
      { name: 'SQL to XML Converter', to: 'sql-converters/sql-to-xml' },
      { name: 'SQL to YAML Converter', to: 'sql-converters/sql-to-yaml' },
      { name: 'SQL to HTML Converter', to: 'sql-converters/sql-to-html' }
    ]
  },
  {
    name: 'encode-&-decode',
    subcategories: [
      { name: 'Base32 Encode', to: 'encode-&-decode/base32-encode' },
      { name: 'Base32 Decode', to: 'encode-&-decode/base32-decode' },
      { name: 'Base58 Encode', to: 'encode-&-decode/base58-encode' },
      { name: 'Base58 Decode', to: 'encode-&-decode/base58-decode' },
      { name: 'Base64 Encode', to: 'encode-&-decode/base64-encode' },
      { name: 'Base64 Decode', to: 'vbase64-decode' },
      { name: 'URL Encode Online', to: 'encode-&-decode/url-encode' },
      { name: 'URL Decode Online', to: 'encode-&-decode/url-decode' },
      { name: 'JSON URL Encode', to: 'encode-&-decode/json-url-encode' },
      { name: 'JSON URL Decode', to: 'encode-&-decode/json-url-decode' },
      { name: 'HTML Encode', to: 'encode-&-decode/html-encode' },
      { name: 'HTML Decode', to: 'encode-&-decode/html-decode' },
      { name: 'XML URL Encoding', to: 'encode-&-decode/xml-url-encode' },
      { name: 'XML URL Decoding', to: 'encode-&-decode/xml-url-decode' },
      { name: 'UTF8 Converter', to: 'encode-&-decode/utf8-converter' },
      { name: 'UTF8 Decode', to: 'encode-&-decode/utf8-decode' },
      { name: 'Hex to UTF8', to: 'encode-&-decode/hex-to-utf8' },
      { name: 'JSON Decode Online', to: 'encode-&-decode/json-decode' },
      { name: 'JSON Encode Online', to: 'encode-&-decode/json-encode' }
    ]
  },
  {
    name: 'base64-tools', href: '/base64-tools',
    subcategories: [
      { name: 'Image to Base64', to: 'base64-tools/image-to-base64' },
      { name: 'Base64 to Image', to: 'base64-tools/base64-to-image' },
      { name: 'PNG to Base64', to: 'base64-tools/png-to-base64' },
      { name: 'JPG to Base64', to: 'base64-tools/jpg-to-base64' },
      { name: 'JSON to Base64', to: 'base64-tools/json-to-base64' },
      { name: 'XML to Base64', to: 'base64-tools/xml-to-base64' },
      { name: 'YAML to Base64', to: 'base64-tools/yaml-to-base64' },
      { name: 'Base64 to JSON', to: 'base64-tools/base64-to-json' },
      { name: 'Base64 to XML', to: 'base64-tools/base64-to-xml' },
      { name: 'Base64 to YAML', to: 'base64-tools/base64-to-yaml' },
      { name: 'CSV to Base64', to: 'base64-tools/csv-to-base64' },
      { name: 'Base64 to CSV', to: 'base64-tools/base64-to-csv' },
      { name: 'TSV to Base64', to: 'base64-tools/tsv-to-base64' },
      { name: 'Base64 to TSV', to: 'base64-tools/base64-to-tsv' },
      { name: 'Binary to Base64', to: 'base64-tools/binary-to-base64' },
      { name: 'Base64 to Binary', to: 'base64-tools/base64-to-binary' },
      { name: 'Hex to Base64', to: 'base64-tools/hex-to-base64' },
      { name: 'Base64 to Hex', to: 'base64-tools/base64-to-hex' },
      { name: 'Octal to Base64', to: 'base64-tools/octal-to-base64' },
      { name: 'More Base64 Tools', to: 'base64-tools/more-base64-tools' }
    ]
  },
  {
    name: 'image-tools', href: '/image-tools',
    subcategories: [
      { name: 'JPG to PNG', to: 'image-tools/jpg-to-png' },
      { name: 'BMP to PNG', to: 'image-tools/bmp-to-png' },
      { name: 'PNG to JPG', to: 'image-tools/png-to-jpg' },
      { name: 'GIF Splitter', to: 'image-tools/gif-splitter' },
      { name: 'GIF Viewer', to: 'image-tools/gif-viewer' },
      { name: 'More Image Tools', to: 'image-tools/more-image-tools' }
    ]
  },

  {
    name: 'json-converters', href: '/json-converters',
    subcategories: [
      { name: 'JSON to JAVA', to: 'json-converters/json-to-java' },
      { name: 'JSON to XML', to: 'json-converters/json-to-xml' },
      { name: 'JSON to YAML', to: 'json-converters/json-to-yaml' },
      { name: 'JSON to CSV', to: 'json-converters/json-to-csv' },
      { name: 'JSON to TSV', to: 'json-converters/json-to-tsv' },
      { name: 'JSON to Text', to: 'json-converters/json-to-text' },
      { name: 'JSON to Excel', to: 'json-converters/json-to-excel' },
      { name: 'JSON to HTML', to: 'json-converters/json-to-html' }
    ]
  },
  {
    name: 'XML Converters', href: '/xml-converters',
    subcategories: [
      { name: 'XML Converter', to: 'XML-Converters/xml-converter' },
      { name: 'XML to JSON', to: 'XML-Converters/xml-to-json' },
      { name: 'XML to YAML', to: 'XML-Converters/xml-to-yaml' },
      { name: 'XML to CSV', to: 'XML-Converters/xml-to-csv' },
      { name: 'XML to TSV', to: 'XML-Converters/xml-to-tsv' },
      { name: 'XML to Text', to: 'XML-Converters/xml-to-text' },
      { name: 'XML-XSL Transform', to: 'XML-Converters/xml-xsl-transform' },
      { name: 'XML to HTML', to: 'XML-Converters/xml-to-html' },
      { name: 'XML to Excel', to: 'XML-Converters/xml-to-excel' },
      { name: 'XML to JAVA', to: 'XML-Converters/xml-to-java' }
    ]
  },
  {
    name: 'HTML Converters', href: '/html-converters',
    subcategories: [
      { name: 'HTML Stripper', to: 'html-stripper' },
      { name: 'HTML Table Generator', to: 'HTML-Converters/html-table-generator' },
      { name: 'HTML to CSV Converter', to: 'HTML-Converters/html-to-csv-converter' },
      { name: 'HTML to TSV Converter', to: 'HTML-Converters/html-to-tsv-converter' },
      { name: 'HTML to PHP Converter', to: 'HTML-Converters/html-to-php-converter' },
      { name: 'HTML to CSV', to: 'HTML-Converters/html-to-csv' },
      { name: 'HTML to JSON', to: 'HTML-Converters/html-to-json' },
      { name: 'HTML to XML', to: 'HTML-Converters/html-to-xml' },
      { name: 'HTML to YAML', to: 'HTML-Converters/html-to-yaml' },
      { name: 'HTML to Text', to: 'HTML-Converters/html-to-text' },
      { name: 'Text to HTML Entities', to: 'HTML-Converters/text-to-html-entities' },
      { name: 'HTML Entities to Text', to: 'HTML-Converters/html-entities-to-text' },
      { name: 'HTML to Markdown', to: 'HTML-Converters/html-to-markdown' },
      { name: 'Markdown to HTML', to: 'HTML-Converters/markdown-to-html' },
      { name: 'PUG to HTML Converter', to: 'HTML-Converters/pug-to-html-converter' },
      { name: 'HTML to PUG Converter', to: 'HTML-Converters/html-to-pug-converter' },
      { name: 'JADE to HTML Converter', to: 'HTML-Converters/jade-to-html-converter' },
      { name: 'HTML to JADE Converter', to: 'HTML-Converters/html-to-jade-converter' },
      { name: 'HTML to BBCode Converter', to: 'HTML-Converters/html-to-bbcode-converter' },
      { name: 'BBCode to HTML Converter', to: 'HTML-Converters/bbcode-to-html-converter' }
    ]
  },
  {
    name: 'yaml-converters', href: '/yaml-converters',
    subcategories: [
      { name: 'YAML Converter', to: 'yaml-converters/yaml-converter' },
      { name: 'YAML to JSON', to: 'yaml-converters/yaml-to-json' },
      { name: 'YAML to XML', to: 'yaml-converters/yaml-to-xml' },
      { name: 'YAML to CSV', to: 'yaml-converters/yaml-to-csv' },
      { name: 'YAML to TSV', to: 'yaml-converters/yaml-to-tsv' },
      { name: 'YAML to TEXT', to: 'yaml-converters/yaml-to-text' },
      { name: 'YAML to HTML', to: 'yaml-converters/yaml-to-html' },
    ]
  },
  {
    name: 'utility', href: '/utility',
    subcategories: [
      { name: 'Send Snap Message', to: 'Utility/send-snap-message' },
      { name: 'Responsive Website Tester', to: 'Utility/responsive-website-tester' },
      { name: 'Credit Card Validator', to: 'Utility/credit-card-validator' },
      { name: 'Credit Card Fake Number Generator', to: 'Utility/credit-card-fake-number-generator' },
      { name: 'XPath Tester', to: 'Utility/xpath-tester' },
      { name: 'JSON Path Tester', to: 'Utility/json-path-tester' },
      { name: 'JSON Minifier', to: 'Utility/json-minifier' },
      { name: 'File Difference', to: 'Utility/file-difference' },
      { name: 'JSON Diff', to: 'Utility/json-diff' },
      { name: 'XML Diff', to: 'Utility/xml-diff' },
      { name: 'Broken Link Checker', to: 'Utility/broken-link-checker' },
      { name: 'JSON Deserialize Online', to: 'Utility/json-deserialize-online' },
      { name: 'JSON Serialize Online', to: 'Utility/json-serialize-online' },
      { name: 'JSON Stringify Online', to: 'Utility/json-stringify-online' },
      { name: 'XML Stringify Online', to: 'Utility/xml-stringify-online' },
      { name: 'String to JSON Online', to: 'Utility/string-to-json-online' },
      { name: 'JavaScript Obfuscator', to: 'Utility/javascript-obfuscator' },
      { name: 'Curl to PHP', to: 'Utility/curl-to-php' },
      { name: 'Crontab Format', to: 'Utility/crontab-format' }
    ]
  },
];
export const categories = [
  { id: 'home', name: 'Home Page', icon: "Sparkles" },
  { id: 'popular', name: 'Popular Tools', icon: "TrendingUp" },
  { id: 'navbar', name: 'Navbar', icon: "SiNaver" },
  { id: 'trendingtools', name: 'Trending Tools', icon: "Sparkles" },
  { id: 'encode_decode', name: 'Encode / Decode', icon: "Shield" },
  { id: 'base64_tools', name: 'Base64 Tools', icon: "Layers" },
  { id: 'html_converters', name: 'HTML Converters', icon: "FileText" },
  { id: 'json_converters', name: 'JSON Converters', icon: "Braces" },
  { id: 'xml_converters', name: 'XML Converters', icon: "FileText" },
  { id: 'yaml_converters', name: 'YAML Converters', icon: "FileText" },
  { id: 'sql_converters', name: 'SQL Converters', icon: "Database" },
  { id: 'image_tools', name: 'Image Tools', icon: "Image" },
  { id: 'nf', name: 'New Features', icon: "Sparkles" },
  { id: 'pdf', name: 'PDF Tools', icon: "PDF" },
];
export const GUIDES = {
  'web-to-pdf-guide': {
    title: 'How to Save a Web Page as PDF',
    steps: [
      {
        t: 'Chrome / Edge / Firefox',
        d: 'Press Ctrl+P (Cmd+P on Mac) → Set Destination to "Save as PDF" → Click Save.',
      },
      { t: 'Safari on Mac', d: 'File menu → Export as PDF → Choose location and save.' },
      { t: 'iPhone / iPad', d: 'Share button → Options → PDF → Save to Files.' },
      { t: 'Android Chrome', d: 'Three-dot menu → Share → Print → Save as PDF.' },
      {
        t: 'Using HTML to PDF tool above',
        d: 'Save the webpage as HTML file (Ctrl+S), then upload the HTML file here.',
      },
    ],
  },
  'sign-guide': {
    title: 'How to Electronically Sign a PDF',
    steps: [
      {
        t: 'Use our Sign PDF tool',
        d: 'Upload PDF → Draw your signature in the canvas → Click Apply → Download signed PDF.',
      },
      {
        t: 'Adobe Acrobat Reader (Free)',
        d: 'Open PDF → Fill & Sign → Draw or type signature → Position it → Save.',
      },
      {
        t: 'Preview on Mac',
        d: 'Open in Preview → Markup toolbar → Signature → Create → Drag onto document.',
      },
      { t: 'Microsoft Edge', d: 'Open PDF in Edge → Draw tool → Sign → Save a copy.' },
      {
        t: 'Online: DocuSign / HelloSign',
        d: 'These services provide legally binding electronic signatures.',
      },
    ],
  },
  'split-guide': {
    title: 'How to Split PDF Pages',
    steps: [
      {
        t: 'Use our Split PDF tool',
        d: 'Upload PDF → Enter ranges like "1-3, 4-6" → Each range downloads as a PDF.',
      },
      { t: 'Extract a single page', d: 'Enter just "3" to extract only page 3 as its own PDF.' },
      { t: 'Split every page', d: 'Leave range blank — splits every page into individual PDFs.' },
      { t: 'Adobe Acrobat (paid)', d: 'Tools → Organize Pages → Split → set pages per file.' },
    ],
  },
  'fill-guide': {
    title: 'How to Fill Out a PDF Form',
    steps: [
      {
        t: 'Use our Fill PDF Form tool',
        d: 'Upload PDF → Click "Load Form Fields" → Fill in values → Download.',
      },
      {
        t: 'Adobe Acrobat Reader (Free)',
        d: 'Open PDF → form fields are clickable — type, check boxes, sign. Save.',
      },
      { t: 'Chrome Browser', d: 'Open PDF in Chrome → click on form fields and type directly.' },
      {
        t: 'Preview on Mac',
        d: 'Open PDF → form fields auto-detected → click and fill → Export as PDF.',
      },
      {
        t: 'Non-fillable PDF?',
        d: 'Use our Edit PDF tool to add text boxes over the field areas manually.',
      },
    ],
  },
  'excel-tips': {
    title: 'Excel Tips & Tricks',
    steps: [
      {
        t: 'Add a tick/checkmark (✓)',
        d: 'Method 1: In a cell type =CHAR(252) and set font to Wingdings. Method 2: Insert → Symbol → Wingdings font → select ✓.',
      },
      {
        t: 'Number pages in Excel',
        d: 'Insert → Header & Footer → click footer section → Insert Page Number. Format: &[Page] of &[Pages].',
      },
      {
        t: 'Un-concatenate / split text',
        d: 'Use Data → Text to Columns. Or formulas: =LEFT(A1,3), =RIGHT(A1,3), =MID(A1,2,4).',
      },
      {
        t: 'Check duplicates in Excel',
        d: 'Home → Conditional Formatting → Highlight Cell Rules → Duplicate Values. Or use our Duplicate Checker tool.',
      },
      {
        t: 'Remove blank lines',
        d: 'Ctrl+G → Special → Blanks → Right-click → Delete Entire Row. Or use our Remove Blank Rows tool.',
      },
      {
        t: 'How to accept edits in Word',
        d: 'Review tab → Accept → Accept All Changes. Or right-click a tracked change → Accept.',
      },
      {
        t: 'Remove page corners/borders in Word',
        d: 'Design tab → Page Borders → None → OK. For text box borders: right-click → Format Shape → No line.',
      },
    ],
  },
  'pdf-to-ppt': {
    title: 'PDF to PowerPoint',
    steps: [
      {
        t: 'Step 1: Convert PDF pages to images',
        d: 'Use our "PDF to JPG" tool to download each page as a JPG image.',
      },
      { t: 'Step 2: Create new PowerPoint', d: 'Open PowerPoint → New blank presentation.' },
      {
        t: 'Step 3: Insert images as slides',
        d: 'For each slide: Insert → Pictures → select the page JPG → resize to fill slide.',
      },
      {
        t: 'Online tools',
        d: 'SmallPDF.com, ILovePDF.com, and Adobe Acrobat (paid) can convert PDF to PPTX directly.',
      },
      {
        t: 'LibreOffice Impress (Free)',
        d: 'Open LibreOffice Impress → Insert → Image for each PDF page image.',
      },
    ],
  },
};

 export const footerSections = [
    {
      title: 'Popular Functionality',
      links: [
        // { name: 'JSON Beautifier', href: '/json-formatter' },
        { name: 'HTML Viewer', href: '/html-converters/html-stripper' },
        { name: 'Number to Words', href: '/popular/number-to-words' },
        { name: 'SQL Formatter', href: '/sql-converters/sql-to-csv' },
        { name: 'Image to Base64', href: '/base64-tools/image-to-base64' },
        { name: 'Base64 to Image', href: '/base64-tools/base64-to-image' },
        { name: 'HEX to Pantone', href: '/popular/hex-to-pantone' },
        { name: 'Source Code Viewer', href: '/popular/source-code-viewer' },
        { name: 'Binary to Text', href: '/encode-decode/base64-decode' },
        // { name: 'JSON Viewer', href: '/json-formatter' },
        // { name: 'JSON Validator', href: '/json-formatter' },
        { name: 'Base64 Decode', href: '/encode-decode/base64-decode' },
        { name: 'Hex to Decimal', href: '/popular/hex-to-decimal' },
        { name: 'XML Viewer', href: '/xml-converters/xml-viewer' },
        { name: 'XML to JSON', href: '/xml-converters/xml-to-json' },
        { name: 'Encryption-Decryption', href: '/encode-decode/base64-encode' },
        { name: 'Excel to HTML', href: '/popular/excel-to-html' },
        { name: 'CSS Validator', href: '/popular/css-validator' },
        // { name: 'XML Validator', href: '/xml-formatter' },
        { name: 'JavaScript Validator', href: '/popular/javascript-validator' },
        { name: 'CSS Beautifier', href: '/popular/css-beautifier' },
        // { name: 'ONLINE JSON EDITOR', href: '/json-formatter' },
        { name: 'Decimal to Hex', href: '/popular/decimal-to-hex' },
        { name: 'Binary to Decimal', href: '/popular/binary-to-decimal' },
        { name: 'ASCII to Text', href: '/encode-decode/base64-decode' },
        { name: 'Random Emoji Generator', href: '/popular/random-emoji-generator' },
        { name: 'REM to PX Converter', href: '/popular/rem-to-px-converter' },
        { name: 'Incorrect Quotes Generator', href: '/popular/incorrect-quotes-generator' },
        { name: 'Lua Beautifier', href: '/trendingtool/lua-beautifier' }
      ]
    },
    {
      title: 'Trending Tools',
      links: [
        { name: 'Bitwise Calculator', href: '/trendingtool/number-utilities' },
        { name: 'Number Sorter', href: '/trendingtool/number-utilities' },
        { name: 'Remove Punctuation', href: '/trendingtool/number-utilities' },
        { name: 'HTML Stripper', href: '/trendingtool/html-stripper' },
        { name: 'Real Time HTML Editor', href: '/html-converters/html-stripper' },
        { name: 'HTML to Markdown', href: '/html-converters/html-to-markdown' },
        { name: 'Markdown to HTML', href: '/html-converters/markdown-to-html' },
        { name: 'Lua Minifier', href: '/trendingtool/lua-minifier' },
        { name: 'Lua Beautifier', href: '/trendingtool/lua-beautifier' },
        { name: 'WordPress Password Hash', href: '/trendingtool/wordpress-password-hash' },
        { name: 'Mirror Online', href: '/trendingtool/mirror-online' },
        { name: 'PHP Formatter', href: '/trendingtool/php-formatter' },
        { name: 'Image to ASCII Art', href: '/trendingtool/image-to-ascii-art' },
        { name: 'SHA256 Hash Generator', href: '/trendingtool/sha256' },
        { name: 'SHA512 Hash Generator', href: '/trendingtool/sha512' },
        { name: 'Excel Viewer', href: '/trendingtool/excel-viewer' },
        { name: 'Paraphrasing Tool', href: '/trendingtool/paraphrasing-tool' },
        { name: 'Word to HTML', href: '/trendingtool/word-to-html' },
        { name: 'CSV to Excel', href: '/trendingtool/csv-to-excel' },
        { name: 'Sharelink Generator', href: '/trendingtool/sharelink-generator' }
      ]
    },
    {
      title: 'Developer Tools',
      links: [
        { name: 'IP Tools', href: '/' },
        // { name: 'Formatters & Beautifiers', href: '/json-formatter' },
        { name: 'Image Converter Tools', href: '/image-tools/jpg-to-png' },
        { name: 'Finance Tools', href: '/' },
        { name: 'TSV Tools', href: '/json-converters/json-to-tsv' },
        // { name: 'JSON Tools', href: '/json-formatter' },
        // { name: 'XML Tools', href: '/xml-formatter' },
        { name: 'YAML Tools', href: '/yaml-converters/yaml-to-json' },
        { name: 'HTML Tools', href: '/html-converters/html-stripper' },
        { name: 'CSS Tools', href: '/popular/css-beautifier' },
        { name: 'JavaScript Tools', href: '/popular/javascript-validator' },
        { name: 'CSV Tools', href: '/json-converters/json-to-csv' },
        { name: 'SQL Tools', href: '/sql-converters/sql-to-csv' },
        { name: 'Color Tools', href: '/popular/hex-to-pantone' },
        { name: 'Unit Tools', href: '/popular/rem-to-px-converter' },
        { name: 'Number Tools', href: '/popular/number-to-words' },
        { name: 'String Tools', href: '/trendingtool/number-utilities' },
        { name: 'Base64 Tools', href: '/base64-tools/image-to-base64' },
        { name: 'Random Tools', href: '/popular/random-emoji-generator' },
        { name: 'Minifiers', href: '/minifier/json-minify' },
        { name: 'Validators', href: '/popular/css-validator' },
        { name: 'Cryptography', href: '/trendingtool/sha256' },
        { name: 'Escape Unescape Tools', href: '/encode-decode/url-encode' },
        { name: 'UTF Tools', href: '/encode-decode/utf8-encode' },
        { name: 'Compress Decompress', href: '/minifier/json-minify' },
        { name: 'HTML Generators', href: '/html-converters/html-table-generator' },
        { name: 'CSS Generators', href: '/popular/css-beautifier' },
        { name: 'Other Tools', href: '/' },
        { name: 'Text Style Tools', href: '/json-converters/json-to-text' },
        { name: 'CSS Unit Converter Tools', href: '/popular/rem-to-px-converter' },
        { name: 'POJO Tools', href: '/json-converters/json-to-java' },
        { name: 'Twitter Tools', href: '/' },
        { name: 'Random Generators', href: '/popular/random-emoji-generator' }
      ]
    }
  ];


  export const CATEGORIES = [
  {
    id: 'image',
    label: 'Image',
    icon: '🖼️',
    color: 'text-violet-400',
    bg: 'bg-violet-500/10 border-violet-500/20',
    tools: [
      {
        id: 'png',
        name: 'PNG Compressor',
        description: 'Losslessly shrink PNG files without quality loss.',
        tags: ['png', 'lossless', 'image'],
        popular: true,
      },
      {
        id: 'jpg',
        name: 'JPG Compressor',
        description: 'Reduce JPG file sizes with smart quality control.',
        tags: ['jpg', 'jpeg', 'lossy'],
        popular: true,
      },
      {
        id: 'jpeg',
        name: 'JPEG Compressor',
        description: 'Optimise JPEG images for web and email.',
        tags: ['jpeg', 'jpg', 'image'],
      },
      {
        id: 'webp',
        name: 'WEBP Compressor',
        description: 'Compress modern WebP images efficiently.',
        tags: ['webp', 'modern', 'image'],
        new: true,
      },
      {
        id: 'gif',
        name: 'GIF Compressor',
        description: 'Reduce animated GIF file sizes.',
        tags: ['gif', 'animated', 'image'],
      },
      {
        id: 'svg',
        name: 'SVG Compressor',
        description: 'Minify and compress SVG vector files.',
        tags: ['svg', 'vector', 'minify'],
      },
      {
        id: 'avif',
        name: 'AVIF Compressor',
        description: 'Compress next-gen AVIF image format.',
        tags: ['avif', 'next-gen', 'image'],
        new: true,
      },
      {
        id: 'heic',
        name: 'HEIC Compressor',
        description: 'Compress Apple HEIC/HEIF photos.',
        tags: ['heic', 'apple', 'photo'],
      },
      {
        id: 'bmp',
        name: 'BMP Compressor',
        description: 'Compress legacy BMP bitmap images.',
        tags: ['bmp', 'bitmap', 'legacy'],
      },
      {
        id: 'tiff',
        name: 'TIFF Compressor',
        description: 'Reduce TIFF file sizes for print/scan.',
        tags: ['tiff', 'print', 'scan'],
      },
      {
        id: 'ico',
        name: 'ICO Compressor',
        description: 'Compress website favicon ICO files.',
        tags: ['ico', 'favicon', 'icon'],
      },
      {
        id: 'raw',
        name: 'RAW Compressor',
        description: 'Compress camera RAW image files.',
        tags: ['raw', 'camera', 'photo'],
      },
      {
        id: 'psd',
        name: 'PSD Compressor',
        description: 'Reduce Photoshop PSD file sizes.',
        tags: ['psd', 'photoshop', 'design'],
      },
      {
        id: 'ai-img',
        name: 'AI Image Compressor',
        description: 'AI-powered intelligent image compression.',
        tags: ['ai', 'smart', 'image'],
        badge: 'AI',
      },
      {
        id: 'eps',
        name: 'EPS Compressor',
        description: 'Compress EPS vector/postscript files.',
        tags: ['eps', 'vector', 'print'],
      },
      {
        id: 'tga',
        name: 'TGA Compressor',
        description: 'Compress TGA game/rendering textures.',
        tags: ['tga', 'game', 'texture'],
      },
      {
        id: 'lossless',
        name: 'Lossless Compressor',
        description: 'Zero quality loss image compression.',
        tags: ['lossless', 'quality', 'image'],
      },
      {
        id: 'lossy',
        name: 'Lossy Compressor',
        description: 'Aggressive size reduction with minimal visual impact.',
        tags: ['lossy', 'size', 'image'],
      },
      {
        id: 'smart-img',
        name: 'Smart Image Compressor',
        description: 'Automatically chooses best compression method.',
        tags: ['smart', 'auto', 'image'],
      },
      {
        id: 'bulk-img',
        name: 'Bulk Image Compressor',
        description: 'Compress hundreds of images at once.',
        tags: ['bulk', 'batch', 'image'],
        popular: true,
      },
      {
        id: 'hq-img',
        name: 'High-Quality Compressor',
        description: 'Preserve maximum quality while reducing size.',
        tags: ['quality', 'hq', 'image'],
      },
      {
        id: 'bitrate-img',
        name: 'Image Bitrate Compressor',
        description: 'Fine-tune image bitrate for optimal output.',
        tags: ['bitrate', 'image', 'advanced'],
      },
      {
        id: 'res-img',
        name: 'Image Resolution Compressor',
        description: 'Downscale image resolution smartly.',
        tags: ['resolution', 'resize', 'image'],
      },
    ],
  },
  {
    id: 'video',
    label: 'Video',
    icon: '🎥',
    color: 'text-rose-400',
    bg: 'bg-rose-500/10 border-rose-500/20',
    tools: [
      {
        id: 'mp4',
        name: 'MP4 Compressor',
        description: 'Compress MP4 videos for web and mobile.',
        tags: ['mp4', 'video', 'h264'],
        popular: true,
      },
      {
        id: 'mov',
        name: 'MOV Compressor',
        description: 'Reduce Apple MOV file sizes.',
        tags: ['mov', 'apple', 'video'],
      },
      {
        id: 'avi',
        name: 'AVI Compressor',
        description: 'Compress legacy AVI video files.',
        tags: ['avi', 'legacy', 'video'],
      },
      {
        id: 'mkv',
        name: 'MKV Compressor',
        description: 'Compress Matroska container videos.',
        tags: ['mkv', 'matroska', 'video'],
      },
      {
        id: 'webm',
        name: 'WEBM Compressor',
        description: 'Compress WebM videos for web use.',
        tags: ['webm', 'web', 'video'],
      },
      {
        id: 'flv',
        name: 'FLV Compressor',
        description: 'Compress Flash video files.',
        tags: ['flv', 'flash', 'video'],
      },
      {
        id: 'wmv',
        name: 'WMV Compressor',
        description: 'Reduce Windows Media Video sizes.',
        tags: ['wmv', 'windows', 'video'],
      },
      {
        id: 'm4v',
        name: 'M4V Compressor',
        description: 'Compress iTunes M4V video files.',
        tags: ['m4v', 'itunes', 'apple'],
      },
      {
        id: '3gp',
        name: '3GP Compressor',
        description: 'Compress mobile 3GP videos.',
        tags: ['3gp', 'mobile', 'video'],
      },
      {
        id: 'ogv',
        name: 'OGV Compressor',
        description: 'Compress open OGG video files.',
        tags: ['ogv', 'ogg', 'open'],
      },
      {
        id: '4k',
        name: '4K Video Compressor',
        description: 'Compress ultra-HD 4K footage.',
        tags: ['4k', 'uhd', 'video'],
        popular: true,
      },
      {
        id: 'hd',
        name: 'HD Video Compressor',
        description: 'Reduce HD 1080p/720p video sizes.',
        tags: ['hd', '1080p', 'video'],
      },
      {
        id: 'batch-vid',
        name: 'Batch Video Compressor',
        description: 'Process multiple videos simultaneously.',
        tags: ['batch', 'bulk', 'video'],
      },
      {
        id: 'stream',
        name: 'Streaming Video Compressor',
        description: 'Optimise video for streaming platforms.',
        tags: ['stream', 'hls', 'video'],
      },
      {
        id: 'mobile-vid',
        name: 'Mobile Video Compressor',
        description: 'Optimise videos for mobile devices.',
        tags: ['mobile', 'phone', 'video'],
      },
      {
        id: 'yt-vid',
        name: 'YouTube Video Compressor',
        description: 'Compress videos for YouTube upload.',
        tags: ['youtube', 'social', 'video'],
      },
      {
        id: 'tiktok-vid',
        name: 'TikTok Video Compressor',
        description: 'Optimise videos for TikTok.',
        tags: ['tiktok', 'social', 'video'],
      },
    ],
  },
  {
    id: 'audio',
    label: 'Audio',
    icon: '🎵',
    color: 'text-amber-400',
    bg: 'bg-amber-500/10 border-amber-500/20',
    tools: [
      {
        id: 'mp3',
        name: 'MP3 Compressor',
        description: 'Reduce MP3 audio file sizes.',
        tags: ['mp3', 'audio', 'music'],
        popular: true,
      },
      {
        id: 'wav',
        name: 'WAV Compressor',
        description: 'Compress uncompressed WAV audio.',
        tags: ['wav', 'lossless', 'audio'],
      },
      {
        id: 'aac',
        name: 'AAC Compressor',
        description: 'Optimise AAC audio for streaming.',
        tags: ['aac', 'streaming', 'audio'],
      },
      {
        id: 'ogg',
        name: 'OGG Compressor',
        description: 'Compress open OGG audio files.',
        tags: ['ogg', 'open', 'audio'],
      },
      {
        id: 'flac',
        name: 'FLAC Compressor',
        description: 'Reduce lossless FLAC file sizes.',
        tags: ['flac', 'lossless', 'audio'],
      },
      {
        id: 'm4a',
        name: 'M4A Compressor',
        description: 'Compress Apple M4A audio files.',
        tags: ['m4a', 'apple', 'audio'],
      },
      {
        id: 'wma',
        name: 'WMA Compressor',
        description: 'Compress Windows Media Audio.',
        tags: ['wma', 'windows', 'audio'],
      },
      {
        id: 'amr',
        name: 'AMR Compressor',
        description: 'Compress phone call AMR audio.',
        tags: ['amr', 'phone', 'audio'],
      },
      {
        id: 'aiff',
        name: 'AIFF Compressor',
        description: 'Compress Apple AIFF audio files.',
        tags: ['aiff', 'apple', 'audio'],
      },
      {
        id: 'podcast',
        name: 'Podcast Audio Compressor',
        description: 'Optimise audio for podcast distribution.',
        tags: ['podcast', 'voice', 'audio'],
      },
      {
        id: 'batch-aud',
        name: 'Batch Audio Compressor',
        description: 'Compress multiple audio files at once.',
        tags: ['batch', 'bulk', 'audio'],
      },
      {
        id: 'smart-aud',
        name: 'Smart Audio Compressor',
        description: 'AI-driven audio compression.',
        tags: ['smart', 'ai', 'audio'],
        badge: 'AI',
      },
    ],
  },
  {
    id: 'document',
    label: 'Document',
    icon: '📄',
    color: 'text-sky-400',
    bg: 'bg-sky-500/10 border-sky-500/20',
    tools: [
      {
        id: 'pdf',
        name: 'PDF Compressor',
        description: 'Reduce PDF sizes without losing readability.',
        tags: ['pdf', 'document'],
        popular: true,
      },
      {
        id: 'word',
        name: 'Word Compressor',
        description: 'Compress Word .docx documents.',
        tags: ['word', 'docx', 'document'],
      },
      {
        id: 'doc',
        name: 'DOC Compressor',
        description: 'Compress legacy Word .doc files.',
        tags: ['doc', 'word', 'legacy'],
      },
      {
        id: 'docx',
        name: 'DOCX Compressor',
        description: 'Reduce modern Word document sizes.',
        tags: ['docx', 'word', 'document'],
      },
      {
        id: 'excel',
        name: 'Excel Compressor',
        description: 'Compress Excel spreadsheets.',
        tags: ['excel', 'xlsx', 'spreadsheet'],
      },
      {
        id: 'xls',
        name: 'XLS Compressor',
        description: 'Compress legacy Excel files.',
        tags: ['xls', 'excel', 'legacy'],
      },
      {
        id: 'xlsx',
        name: 'XLSX Compressor',
        description: 'Reduce modern Excel file sizes.',
        tags: ['xlsx', 'excel', 'spreadsheet'],
      },
      {
        id: 'ppt',
        name: 'PowerPoint Compressor',
        description: 'Compress PowerPoint presentations.',
        tags: ['ppt', 'powerpoint', 'slides'],
      },
      {
        id: 'pptx',
        name: 'PPTX Compressor',
        description: 'Reduce modern PowerPoint sizes.',
        tags: ['pptx', 'slides', 'presentation'],
      },
      {
        id: 'epub',
        name: 'EPUB Compressor',
        description: 'Compress eBook EPUB files.',
        tags: ['epub', 'ebook', 'book'],
      },
      {
        id: 'rtf',
        name: 'RTF Compressor',
        description: 'Compress Rich Text Format files.',
        tags: ['rtf', 'text', 'document'],
      },
      {
        id: 'txt',
        name: 'TXT Compressor',
        description: 'Compress plain text files.',
        tags: ['txt', 'text', 'plain'],
      },
    ],
  },
  {
    id: 'archive',
    label: 'Archive',
    icon: '📦',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10 border-emerald-500/20',
    tools: [
      {
        id: 'zip',
        name: 'ZIP Compressor',
        description: 'Create and compress ZIP archives.',
        tags: ['zip', 'archive'],
        popular: true,
      },
      {
        id: 'rar',
        name: 'RAR Compressor',
        description: 'Compress files into RAR archives.',
        tags: ['rar', 'archive'],
      },
      {
        id: '7z',
        name: '7Z Compressor',
        description: 'Ultra-high 7-Zip compression.',
        tags: ['7z', '7zip', 'archive'],
      },
      {
        id: 'tar',
        name: 'TAR Compressor',
        description: 'Create TAR archive bundles.',
        tags: ['tar', 'unix', 'archive'],
      },
      {
        id: 'gzip',
        name: 'GZIP Compressor',
        description: 'GZIP compress files for servers.',
        tags: ['gzip', 'gz', 'web'],
      },
      {
        id: 'bzip2',
        name: 'BZIP2 Compressor',
        description: 'High-ratio BZIP2 compression.',
        tags: ['bzip2', 'bz2', 'linux'],
      },
      {
        id: 'xz',
        name: 'XZ Compressor',
        description: 'Extreme XZ/LZMA2 compression.',
        tags: ['xz', 'lzma', 'linux'],
      },
      {
        id: 'zstd',
        name: 'ZSTD Compressor',
        description: 'Fast modern Zstandard compression.',
        tags: ['zstd', 'fast', 'modern'],
        new: true,
      },
      {
        id: 'lzma',
        name: 'LZMA Compressor',
        description: 'High-ratio LZMA compression.',
        tags: ['lzma', '7z', 'archive'],
      },
      {
        id: 'lz4',
        name: 'LZ4 Compressor',
        description: 'Ultra-fast LZ4 compression.',
        tags: ['lz4', 'fast', 'archive'],
        new: true,
      },
      {
        id: 'folder',
        name: 'Folder Compressor',
        description: 'Compress entire directories.',
        tags: ['folder', 'directory', 'bulk'],
      },
      {
        id: 'email-att',
        name: 'Email Attachment Compressor',
        description: 'Shrink files for email attachments.',
        tags: ['email', 'attachment', 'send'],
      },
    ],
  },
  {
    id: 'developer',
    label: 'Developer',
    icon: '💻',
    color: 'text-lime-400',
    bg: 'bg-lime-500/10 border-lime-500/20',
    tools: [
      {
        id: 'html-min',
        name: 'HTML Minifier',
        description: 'Strip blackspace from HTML files.',
        tags: ['html', 'minify', 'web'],
        popular: true,
      },
      {
        id: 'css-min',
        name: 'CSS Minifier',
        description: 'Minify CSS stylesheets.',
        tags: ['css', 'minify', 'web'],
        popular: true,
      },
      {
        id: 'js-min',
        name: 'JavaScript Minifier',
        description: 'Minify and compress JS bundles.',
        tags: ['js', 'javascript', 'minify'],
        popular: true,
      },
      {
        id: 'json-min',
        name: 'JSON Minifier',
        description: 'Compress and minify JSON data.',
        tags: ['json', 'minify', 'data'],
      },
      {
        id: 'xml-min',
        name: 'XML Minifier',
        description: 'Minify XML markup files.',
        tags: ['xml', 'minify', 'data'],
      },
      {
        id: 'sql-min',
        name: 'SQL Query Compressor',
        description: 'Minify SQL queries.',
        tags: ['sql', 'database', 'query'],
      },
      {
        id: 'php',
        name: 'PHP Code Compressor',
        description: 'Minify PHP source files.',
        tags: ['php', 'server', 'code'],
      },
      {
        id: 'python',
        name: 'Python Code Compressor',
        description: 'Minify Python scripts.',
        tags: ['python', 'code', 'script'],
      },
      {
        id: 'java',
        name: 'Java Code Compressor',
        description: 'Compress Java source files.',
        tags: ['java', 'code', 'jvm'],
      },
      {
        id: 'cpp',
        name: 'C++ Code Compressor',
        description: 'Minify C++ source code.',
        tags: ['cpp', 'c++', 'native'],
      },
      {
        id: 'ts',
        name: 'TypeScript Compressor',
        description: 'Compress TypeScript files.',
        tags: ['typescript', 'ts', 'code'],
      },
      {
        id: 'jsx',
        name: 'React JSX Compressor',
        description: 'Compress React JSX/TSX files.',
        tags: ['react', 'jsx', 'tsx'],
      },
      {
        id: 'nextjs',
        name: 'Next.js Bundle Compressor',
        description: 'Optimise Next.js production bundles.',
        tags: ['nextjs', 'bundle', 'react'],
      },
      {
        id: 'graphql',
        name: 'GraphQL Compressor',
        description: 'Minify GraphQL queries/schemas.',
        tags: ['graphql', 'api', 'schema'],
      },
      {
        id: 'yaml',
        name: 'YAML Compressor',
        description: 'Compress YAML configuration files.',
        tags: ['yaml', 'config', 'devops'],
      },
      {
        id: 'toml',
        name: 'TOML Compressor',
        description: 'Minify TOML config files.',
        tags: ['toml', 'config', 'rust'],
      },
      {
        id: 'webpack',
        name: 'Webpack Bundle Compressor',
        description: 'Optimise Webpack build output.',
        tags: ['webpack', 'bundle', 'build'],
      },
      {
        id: 'brotli',
        name: 'Brotli Web Compressor',
        description: 'Brotli-compress web assets.',
        tags: ['brotli', 'web', 'server'],
        new: true,
      },
    ],
  },
  {
    id: 'ai',
    label: 'AI / Smart',
    icon: '🧠',
    color: 'text-fuchsia-400',
    bg: 'bg-fuchsia-500/10 border-fuchsia-500/20',
    tools: [
      {
        id: 'ai-image2',
        name: 'AI Image Compressor',
        description: 'Neural-network image compression.',
        tags: ['ai', 'image', 'smart'],
        badge: 'AI',
        popular: true,
      },
      {
        id: 'ai-video',
        name: 'AI Video Compressor',
        description: 'AI-powered video size reduction.',
        tags: ['ai', 'video', 'smart'],
        badge: 'AI',
      },
      {
        id: 'ai-audio',
        name: 'AI Audio Compressor',
        description: 'Machine-learning audio compression.',
        tags: ['ai', 'audio', 'smart'],
        badge: 'AI',
      },
      {
        id: 'ai-file',
        name: 'AI File Compressor',
        description: 'Intelligent all-format compression.',
        tags: ['ai', 'file', 'smart'],
        badge: 'AI',
      },
      {
        id: 'auto',
        name: 'Auto Compression Tool',
        description: 'Detects format and applies best method.',
        tags: ['auto', 'smart', 'all'],
      },
      {
        id: 'ml',
        name: 'ML Compressor',
        description: 'Machine learning-based compression.',
        tags: ['ml', 'ai', 'advanced'],
        badge: 'AI',
      },
      {
        id: 'adaptive',
        name: 'Adaptive Compression',
        description: 'Adapts algorithm to content type.',
        tags: ['adaptive', 'smart', 'dynamic'],
      },
      {
        id: 'gpu',
        name: 'GPU Compressor',
        description: 'GPU-accelerated compression for large files.',
        tags: ['gpu', 'fast', 'accelerated'],
      },
      {
        id: 'parallel',
        name: 'Parallel Compressor',
        description: 'Multi-core parallel compression.',
        tags: ['parallel', 'fast', 'multi-thread'],
      },
    ],
  },
  {
    id: 'social',
    label: 'Social Media',
    icon: '📱',
    color: 'text-pink-400',
    bg: 'bg-pink-500/10 border-pink-500/20',
    tools: [
      {
        id: 'whatsapp',
        name: 'WhatsApp Image Compressor',
        description: 'Optimise images for WhatsApp sharing.',
        tags: ['whatsapp', 'social', 'image'],
        popular: true,
      },
      {
        id: 'instagram',
        name: 'Instagram Image Compressor',
        description: "Compress for Instagram's format.",
        tags: ['instagram', 'social', 'image'],
      },
      {
        id: 'facebook',
        name: 'Facebook Image Compressor',
        description: 'Optimise images for Facebook.',
        tags: ['facebook', 'social', 'image'],
      },
      {
        id: 'youtube2',
        name: 'YouTube Video Compressor',
        description: 'Prepare videos for YouTube upload.',
        tags: ['youtube', 'social', 'video'],
      },
      {
        id: 'tiktok2',
        name: 'TikTok Video Compressor',
        description: 'Compress for TikTok vertical format.',
        tags: ['tiktok', 'social', 'video'],
      },
      {
        id: 'story',
        name: 'Story Image Compressor',
        description: 'Compress story-sized 9:16 images.',
        tags: ['story', 'social', 'image'],
      },
      {
        id: 'thumb',
        name: 'Thumbnail Compressor',
        description: 'Optimise channel/video thumbnails.',
        tags: ['thumbnail', 'youtube', 'image'],
      },
      {
        id: 'screenshot',
        name: 'App Screenshot Compressor',
        description: 'Compress app store screenshots.',
        tags: ['screenshot', 'app', 'image'],
      },
      {
        id: 'social-vid',
        name: 'Social Media Video Compressor',
        description: 'Multi-platform video compression.',
        tags: ['social', 'video', 'multi'],
      },
    ],
  },
];


// ═══════════════════════════════════════════════════════════
// SVG ICONS
// ═══════════════════════════════════════════════════════════
export const I = {
  Bold:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M5 4h5.5a3.5 3.5 0 010 7H5V4zm0 7h6a3.5 3.5 0 010 7H5v-7z"/></svg>,
  Italic:      () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M8 4h6M6 16h6M11 4L9 16"/></svg>,
  Underline:   () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M5 4v7a5 5 0 0010 0V4M3 17h14"/></svg>,
  Strike:      () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M3 10h14M7 6c0-1.1.9-2 2-2h2a2 2 0 012 2v1H7V6zm4 8a2 2 0 002-2v-1H7v1a2 2 0 002 2h2z"/></svg>,
  AlignL:      () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M3 5h14M3 9h8M3 13h12M3 17h6"/></svg>,
  AlignC:      () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M3 5h14M6 9h8M4 13h12M7 17h6"/></svg>,
  AlignR:      () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M3 5h14M9 9h8M5 13h12M11 17h6"/></svg>,
  AlignJ:      () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M3 5h14M3 9h14M3 13h14M3 17h10"/></svg>,
  OL:          () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M2 4h2v4H3V5H2V4zm0 7h2.5c.3 0 .5.2.5.5s-.2.5-.5.5H2v1h2.5c.3 0 .5.2.5.5s-.2.5-.5.5H2v1h3v-1c0-.3.2-.5.5-.5s.5.2.5.5v1.5a.5.5 0 01-.5.5H2a.5.5 0 01-.5-.5V12c0-.6.4-1 1-1zm5-7h9v2H7V4zm0 7h9v2H7v-2zm0 4h9v2H7v-2z"/></svg>,
  UL:          () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><circle cx="3" cy="5" r="1.5"/><circle cx="3" cy="10" r="1.5"/><circle cx="3" cy="15" r="1.5"/><path d="M7 4h10v2H7V4zm0 6h10v2H7v-2zm0 5h10v2H7v-2z"/></svg>,
  Quote:       () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M3 7c0-1.1.9-2 2-2h2a2 2 0 012 2v3a2 2 0 01-2 2H5l-2 3V7zm9 0c0-1.1.9-2 2-2h2a2 2 0 012 2v3a2 2 0 01-2 2h-2l-2 3V7z"/></svg>,
  Link:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M12.586 4.586a2 2 0 112.828 2.828l-3 3a2 2 0 01-2.828 0 1 1 0 00-1.414 1.414 4 4 0 005.656 0l3-3a4 4 0 00-5.656-5.656l-1.5 1.5a1 1 0 001.414 1.414l1.5-1.5zm-5 5a2 2 0 012.828 0 1 1 0 101.414-1.414 4 4 0 00-5.656 0l-3 3a4 4 0 105.656 5.656l1.5-1.5a1 1 0 10-1.414-1.414l-1.5 1.5a2 2 0 11-2.828-2.828l3-3z"/></svg>,
  Unlink:      () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M13 7l-6 6M8.5 4.5l1-1a3.536 3.536 0 015 5l-1 1M11.5 15.5l-1 1a3.536 3.536 0 01-5-5l1-1M3 3l14 14"/></svg>,
  Image:       () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd"/></svg>,
  Undo:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path fillRule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clipRule="evenodd"/></svg>,
  Redo:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"/></svg>,
  Clear:       () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M5 4l10 10M5 14l10-10M3 18h14"/></svg>,
  Indent:      () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M7 5h10v2H7V5zm0 4h10v2H7V9zm0 4h10v2H7v-2zM3 8l3 2.5L3 13V8z"/></svg>,
  Outdent:     () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M7 5h10v2H7V5zm0 4h10v2H7V9zm0 4h10v2H7v-2zM6 8L3 10.5 6 13V8z"/></svg>,
  HR:          () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeLinecap="round" className="w-3.5 h-3.5"><path d="M2 10h16" strokeWidth="2.5"/><path d="M2 5h4M14 5h4M2 15h4M14 15h4" strokeWidth="1"/></svg>,
  Code:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z"/></svg>,
  Sub:         () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><text x="1" y="13" fontSize="10" fontWeight="bold">X</text><text x="9" y="17" fontSize="7">2</text></svg>,
  Sup:         () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><text x="1" y="13" fontSize="10" fontWeight="bold">X</text><text x="9" y="8" fontSize="7">2</text></svg>,
  Table:       () => <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" className="w-3.5 h-3.5"><rect x="2" y="3" width="16" height="14" rx="1"/><path d="M2 8h16M2 13h16M8 3v14M13 3v14"/></svg>,
  Video:       () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M2 6a2 2 0 012-2h6a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V6zm14.553 1.106A1 1 0 0016 8v4a1 1 0 00.553.894l2 1A1 1 0 0020 13V7a1 1 0 00-1.447-.894l-2 1z"/></svg>,
  Emoji:       () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM7 9a1 1 0 100-2 1 1 0 000 2zm7-1a1 1 0 11-2 0 1 1 0 012 0zm-.464 5.535a1 1 0 10-1.415-1.414 3 3 0 01-4.242 0 1 1 0 00-1.415 1.414 5 5 0 007.072 0z" clipRule="evenodd"/></svg>,
  Special:     () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/></svg>,
  Print:       () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path fillRule="evenodd" d="M5 4v3H4a2 2 0 00-2 2v3a2 2 0 002 2h1v2a1 1 0 001 1h8a1 1 0 001-1v-2h1a2 2 0 002-2V9a2 2 0 00-2-2h-1V4a1 1 0 00-1-1H6a1 1 0 00-1 1zm2 0h6v3H7V4zm-1 9v-1h8v3H6v-2h1zm7-5a1 1 0 100-2 1 1 0 000 2z" clipRule="evenodd"/></svg>,
  Fullscreen:  () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M3 3h5v2H5v3H3V3zm9 0h5v5h-2V5h-3V3zM3 12h2v3h3v2H3v-5zm12 3h-3v2h5v-5h-2v3z"/></svg>,
  ExitFull:    () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M7 3H3v4h2V5h2V3zm6 0v2h2v2h2V3h-4zM3 13v4h4v-2H5v-2H3zm12 2h-2v2h4v-4h-2v2z"/></svg>,
  Close:       () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4"><path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd"/></svg>,
  Paste:       () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z"/><path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z"/></svg>,
  Find:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path fillRule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clipRule="evenodd"/></svg>,
  Plus:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3 h-3"><path fillRule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clipRule="evenodd"/></svg>,
  X:           () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3 h-3"><path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd"/></svg>,
  Eye:         () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"/><path fillRule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clipRule="evenodd"/></svg>,
  Moon:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"/></svg>,
  Sun:         () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4"><path fillRule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" clipRule="evenodd"/></svg>,
  Upload:      () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-5 h-5"><path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM6.293 6.707a1 1 0 010-1.414l3-3a1 1 0 011.414 0l3 3a1 1 0 01-1.414 1.414L11 5.414V13a1 1 0 11-2 0V5.414L7.707 6.707a1 1 0 01-1.414 0z" clipRule="evenodd"/></svg>,
  Save:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M7.707 10.293a1 1 0 10-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 11.586V6h5a2 2 0 012 2v7a2 2 0 01-2 2H4a2 2 0 01-2-2V8a2 2 0 012-2h5v5.586l-1.293-1.293zM9 4a1 1 0 012 0v2H9V4z"/></svg>,
  Check:       () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"/></svg>,
  Warn:        () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4"><path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd"/></svg>,
  Spin:        () => <svg className="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>,
  Anchor:      () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M10 2a1 1 0 011 1v1.07A7.002 7.002 0 0116.93 10H18a1 1 0 110 2h-1.07A7.002 7.002 0 0111 17.93V19a1 1 0 11-2 0v-1.07A7.002 7.002 0 013.07 12H2a1 1 0 110-2h1.07A7.002 7.002 0 019 4.07V3a1 1 0 011-1zm0 4a5 5 0 100 10A5 5 0 0010 6zm0 2a1 1 0 011 1v2.586l1.707 1.707a1 1 0 01-1.414 1.414l-2-2A1 1 0 019 12V9a1 1 0 011-1z"/></svg>,
  Highlight:   () => <svg viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zm-2.207 2.207L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"/></svg>,
  Spinner:     () => <svg className="w-5 h-5 animate-spin" viewBox="0 0 24 24" fill="none"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>,
};

// ═══════════════════════════════════════════════════════════
// THEME VARS
// ═══════════════════════════════════════════════════════════
export const light = {
  bg: "bg-[#f1f1f1]", card: "bg-white", border: "border-[#e5e5e5]",
  text: "text-[#23282d]", muted: "text-[#666]",
  toolbar: "bg-[#fafafa]", toolbarBorder: "border-[#e5e5e5]",
  tabBar: "bg-[#f5f5f5]", activeTab: "bg-white",
  inputBorder: "border-[#ddd]", inputFocus: "focus:border-[#0073aa]",
  panelHeader: "bg-[#f5f5f5]",
  btnActive: "bg-[#e5f3fb] border-[#0073aa] text-[#0073aa]",
  btnHover: "hover:bg-[#f0f0f0] hover:border-[#ccc] hover:text-[#23282d]",
  selectCls: "bg-white text-[#23282d] border-[#ddd]",
  statusBar: "bg-[#fafafa] border-[#e5e5e5]",
  publishHeader: "bg-[#23282d] text-white",
  publishFooter: "bg-[#f5f5f5]",
  dropzone: "border-[#ddd] bg-[#fafafa]",
};
export const dark = {
  bg: "bg-[#1a1a1a]", card: "bg-[#252525]", border: "border-[#3a3a3a]",
  text: "text-[#e8e8e8]", muted: "text-[#999]",
  toolbar: "bg-[#2a2a2a]", toolbarBorder: "border-[#3a3a3a]",
  tabBar: "bg-[#1e1e1e]", activeTab: "bg-[#252525]",
  inputBorder: "border-[#444]", inputFocus: "focus:border-[#4a9eff]",
  panelHeader: "bg-[#1e1e1e]",
  btnActive: "bg-[#1a3a5c] border-[#4a9eff] text-[#4a9eff]",
  btnHover: "hover:bg-[#333] hover:border-[#555] hover:text-[#e8e8e8]",
  selectCls: "bg-[#2a2a2a] text-[#e8e8e8] border-[#444]",
  statusBar: "bg-[#1e1e1e] border-[#3a3a3a]",
  publishHeader: "bg-[#111] text-white",
  publishFooter: "bg-[#1e1e1e]",
  dropzone: "border-[#444] bg-[#1e1e1e]",
};

export const ROW1 = [
  { type:"btn", command:"bold",                icon:<I.Bold/>,    title:"Bold (Ctrl+B)" },
  { type:"btn", command:"italic",              icon:<I.Italic/>,  title:"Italic (Ctrl+I)" },
  { type:"btn", command:"underline",           icon:<I.Underline/>,title:"Underline (Ctrl+U)" },
  { type:"btn", command:"strikeThrough",       icon:<I.Strike/>,  title:"Strikethrough" },
  { type:"sep" },
  { type:"btn", command:"justifyLeft",         icon:<I.AlignL/>,  title:"Align Left" },
  { type:"btn", command:"justifyCenter",       icon:<I.AlignC/>,  title:"Align Center" },
  { type:"btn", command:"justifyRight",        icon:<I.AlignR/>,  title:"Align Right" },
  { type:"btn", command:"justifyFull",         icon:<I.AlignJ/>,  title:"Justify" },
  { type:"sep" },
  { type:"btn", command:"insertOrderedList",   icon:<I.OL/>,      title:"Numbered List" },
  { type:"btn", command:"insertUnorderedList", icon:<I.UL/>,      title:"Bullet List" },
  { type:"btn", command:"indent",              icon:<I.Indent/>,  title:"Indent" },
  { type:"btn", command:"outdent",             icon:<I.Outdent/>, title:"Outdent" },
  { type:"sep" },
  { type:"btn", command:"formatBlock", value:"blockquote", icon:<I.Quote/>, title:"Blockquote" },
  { type:"btn", command:"__link__",            icon:<I.Link/>,    title:"Insert/Edit Link" },
  { type:"btn", command:"unlink",              icon:<I.Unlink/>,  title:"Remove Link" },
  { type:"btn", command:"__anchor__",          icon:<I.Anchor/>,  title:"Insert Anchor/ID" },
  { type:"btn", command:"__image__",           icon:<I.Image/>,   title:"Insert Image" },
  { type:"sep" },
  { type:"btn", command:"undo",                icon:<I.Undo/>,    title:"Undo (Ctrl+Z)" },
  { type:"btn", command:"redo",                icon:<I.Redo/>,    title:"Redo (Ctrl+Y)" },
  { type:"sep" },
  { type:"btn", command:"removeFormat",        icon:<I.Clear/>,   title:"Remove Formatting" },
  { type:"btn", command:"insertHorizontalRule",icon:<I.HR/>,      title:"Horizontal Rule" },
];

export const ROW2 = [
  { type:"btn", command:"__table__",   icon:<I.Table/>,   title:"Insert Table" },
  { type:"btn", command:"__video__",   icon:<I.Video/>,   title:"Insert Video" },
  { type:"btn", command:"__emoji__",   icon:<I.Emoji/>,   title:"Insert Emoji" },
  { type:"btn", command:"__special__", icon:<I.Special/>, title:"Special Characters" },
  { type:"sep" },
  { type:"btn", command:"__find__",    icon:<I.Find/>,    title:"Find & Replace" },
  { type:"btn", command:"__paste__",   icon:<I.Paste/>,   title:"Paste as Plain Text" },
  { type:"sep" },
  { type:"btn", command:"subscript",   icon:<I.Sub/>,     title:"Subscript" },
  { type:"btn", command:"superscript", icon:<I.Sup/>,     title:"Superscript" },
  { type:"btn", command:"__code__",    icon:<I.Code/>,    title:"Insert Code Block" },
  { type:"sep" },
  { type:"btn", command:"print",       icon:<I.Print/>,   title:"Print" },
];
 // ── Emoji Picker ────────────────────────────────────────────
export const EMOJI_CATS = {
  "😀 Smileys": ["😀","😂","😍","🤔","😎","🥳","😢","😡","😊","🤩","😴","🤗","😅","😉","😋","🤤","😶","😏","😒","🙃","😌","😔","😪","🥰","🤣","😇","😭","🥺","😤","😠","😈","👻","💀","🎭","🤡"],
  "👍 Gestures": ["👍","👎","❤️","🔥","✅","⚠️","🎉","🚀","💡","📌","🔗","📷","🎵","⭐","💬","📝","🌟","🎯","💪","🙏","👏","🤝","💯","🏆","👑","✨","🌈","🎁","🎊","🎈"],
  "🐶 Animals": ["🐶","🐱","🐭","🐹","🐰","🦊","🐻","🐼","🐨","🐯","🦁","🐮","🐷","🐸","🐵","🐔","🐧","🐦","🦆","🦅","🦉","🦇","🐺","🐗","🐴","🦄"],
  "🍕 Food": ["🍎","🍊","🍋","🍇","🍓","🍒","🥝","🍅","🥑","🍕","🍔","🌮","🍜","🍣","🍦","🎂","☕","🧃","🍺","🥂"],
};

export const SPEC_CATS = {
  "Currency": ["&copy;","&reg;","&trade;","&euro;","&pound;","&yen;","&cent;","&dollar;","&curren;"],
  "Punctuation": ["&mdash;","&ndash;","&hellip;","&laquo;","&raquo;","&ldquo;","&rdquo;","&lsquo;","&rsquo;","&amp;","&lt;","&gt;","&nbsp;","&iexcl;","&iquest;"],
  "Math": ["&deg;","&frac12;","&frac14;","&frac34;","&times;","&divide;","&plusmn;","&ne;","&asymp;","&infin;","&radic;","&sum;","&prod;","&int;","&part;","&forall;","&exist;"],
  "Greek": ["&alpha;","&beta;","&gamma;","&delta;","&epsilon;","&zeta;","&eta;","&theta;","&iota;","&kappa;","&lambda;","&mu;","&nu;","&xi;","&pi;","&rho;","&sigma;","&tau;","&upsilon;","&phi;","&chi;","&psi;","&omega;"],
  "Arrows": ["&larr;","&rarr;","&uarr;","&darr;","&harr;","&lArr;","&rArr;","&uArr;","&dArr;","&hArr;","&crarr;"],
};