import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.aionlinetoolss.com';

  const routes = [
    '',
    // '/json-formatter',
    // '/xml-formatter',
    '/backgroundremover',
    '/videodownloder',
    '/blog',

    // SQL converters
    '/sql-converters/sql-to-csv',
    '/sql-converters/sql-to-json',
    '/sql-converters/sql-to-xml',
    '/sql-converters/sql-to-yaml',
    '/sql-converters/sql-to-html',

    // encode decode
    '/encode-decode/base32-encode',
    '/encode-decode/base32-decode',
    '/encode-decode/base58-encode',
    '/encode-decode/base58-decode',
    '/encode-decode/base64-encode',
    '/encode-decode/base64-decode',
    '/encode-decode/url-encode',
    '/encode-decode/url-decode',
    '/encode-decode/html-encode',
    '/encode-decode/html-decode',
    '/encode-decode/xml-url-encode',
    '/encode-decode/xml-url-decode',
    '/encode-decode/xml-encode',
    '/encode-decode/xml-decode',
    '/encode-decode/utf8-encode',
    '/encode-decode/utf8-decode',
    '/encode-decode/hex-to-utf8',
    '/encode-decode/json-decode',
    '/encode-decode/json-encode',

    // base64 tools
    '/base64-tools/image-to-base64',
    '/base64-tools/base64-to-image',
    '/base64-tools/png-to-base64',
    '/base64-tools/jpeg-to-base64',
    '/base64-tools/gif-to-base64',
    '/base64-tools/jpg-to-base64',

    '/base64-tools/json-to-base64',
    '/base64-tools/xml-to-base64',
    '/base64-tools/yaml-to-base64',
    '/base64-tools/base64-to-json',
    '/base64-tools/base64-to-xml',
    '/base64-tools/base64-to-yaml',
    '/base64-tools/csv-to-base64',
    '/base64-tools/base64-to-csv',
    '/base64-tools/tsv-to-base64',
    '/base64-tools/base64-to-tsv',
    '/base64-tools/binary-to-base64',
    '/base64-tools/base64-to-binary',
    '/base64-tools/hex-to-base64',
    '/base64-tools/base64-to-hex',
    '/base64-tools/octal-to-base64',
    '/base64-tools/base64-to-octal',
    '/base64-tools/html-to-base64',
    '/base64-tools/base64-to-html',
    '/base64-tools/css-to-base64',
    '/base64-tools/base64-to-css',
    '/base64-tools/javascript-to-base64',
    '/base64-tools/base64-to-javascript',
    '/base64-tools/ascii-to-base64',
    '/base64-tools/base64-to-ascii',
    '/base64-tools/text-to-base64',
    '/base64-tools/base64-to-text',
    '/base64-tools/svg-to-base64',
    '/base64-tools/bmp-to-base64',
    '/base64-tools/webp-to-base64',
    '/base64-tools/avif-to-base64',

    // image tools
    '/image-tools/jpg-to-png',
    '/image-tools/png-to-jpg',
    '/image-tools/bmp-to-png',
    '/image-tools/gif-splitter',
    '/image-tools/gif-viewer',

    // json converters
    '/json-converters/json-to-xml',
    '/json-converters/json-to-yaml',
    '/json-converters/json-to-csv',
    '/json-converters/json-to-tsv',
    '/json-converters/json-to-text',
    '/json-converters/json-to-excel',
    '/json-converters/json-to-html',
    '/json-converters/json-to-java',

    // xml converters
    '/xml-converters/xml-to-json',
    '/xml-converters/xml-viewer',
    '/xml-converters/xml-editor',
    '/xml-converters/xml-pretty-print',
    '/xml-converters/xml-converter',
    '/xml-converters/xml-parser-online',
    '/xml-converters/xml-minifier',
    '/xml-converters/xpath-tester',
    '/xml-converters/soap-to-json',
    '/xml-converters/wsdl-to-json',
    '/xml-converters/xml-to-yaml',
    '/xml-converters/xml-to-html',
    '/xml-converters/xml-to-csv',
    '/xml-converters/xml-to-tsv',
    '/xml-converters/xml-to-text',
    '/xml-converters/xml-to-base64',
    '/xml-converters/base64-to-xml',
    '/xml-converters/xml-to-java',
    '/xml-converters/xml-to-excel',

    // html converters
    '/html-converters/html-stripper',
    '/html-converters/html-table-generator',
    '/html-converters/html-to-csv',
    '/html-converters/html-to-tsv',
    '/html-converters/html-to-php',
    '/html-converters/html-to-json',
    '/html-converters/html-to-xml',
    '/html-converters/html-to-yaml',
    '/html-converters/html-to-text',
    '/html-converters/text-to-html-entities',
    '/html-converters/html-entities-to-text',
    '/html-converters/html-to-markdown',
    '/html-converters/markdown-to-html',
    '/html-converters/pug-to-html',
    '/html-converters/html-to-pug',
    '/html-converters/jade-to-html',
    '/html-converters/html-to-jade',
    '/html-converters/html-to-bbcode',
    '/html-converters/bbcode-to-html',

    // yaml converters
    '/yaml-converters/yaml-to-json',
    '/yaml-converters/yaml-to-xml',
    '/yaml-converters/yaml-to-csv',
    '/yaml-converters/yaml-to-tsv',
    '/yaml-converters/yaml-to-text',
    '/yaml-converters/yaml-to-html',

    // minifier
    '/minifier/json-minify',
    '/minifier/xml-minify',
    '/minifier/js-minify',
    '/minifier/css-minify',
    '/minifier/sql-minifier',
    '/minifier/html-minify',
    '/minifier/lua-minifier',
    '/minifier/text-minifier',

    // popular
    '/popular/number-to-words',
    '/popular/hex-to-pantone',
    '/popular/source-code-viewer',
    '/popular/hex-to-decimal',
    '/popular/excel-to-html',
    '/popular/css-validator',
    '/popular/javascript-validator',
    '/popular/css-beautifier',
    '/popular/decimal-to-hex',
    '/popular/binary-to-decimal',
    '/popular/random-emoji-generator',
    '/popular/rem-to-px-converter',
    '/popular/incorrect-quotes-generator',

    // trending tools
    '/trendingtool/number-utilities',
    '/trendingtool/html-stripper',
    '/trendingtool/lua-minifier',
    '/trendingtool/lua-beautifier',
    '/trendingtool/wordpress-password-hash',
    '/trendingtool/mirror-online',
    '/trendingtool/php-formatter',
    '/trendingtool/image-to-ascii-art',
    '/trendingtool/sha256',
    '/trendingtool/sha512',
    '/trendingtool/excel-viewer',
    '/trendingtool/paraphrasing-tool',
    '/trendingtool/word-to-html',
    '/trendingtool/csv-to-excel',
    '/trendingtool/sharelink-generator',

    // pdf tools
    '/pdf-tool/',
    '/pdf-tool/mergepdf',
    '/pdf-tool/splitPDF',
    '/pdf-tool/compressPDF',
    '/pdf-tool/rotatePDF',
    '/pdf-tool/unlock',
    '/pdf-tool/watermark',
    '/pdf-tool/page-numbers',
    '/pdf-tool/repair',
    '/pdf-tool/crop-pdf',
    '/pdf-tool/organize',
    '/pdf-tool/sign-pdf',
    '/pdf-tool/fill-pdf',
    '/pdf-tool/compare-pdf',
    '/pdf-tool/html-to-pdf',
    '/pdf-tool/protect',
    '/pdf-tool/pdf-to-pdfa',
    '/pdf-tool/word-to-pdf',
    '/pdf-tool/csv-to-pdf',
    '/pdf-tool/jpg-to-pdf',
    '/pdf-tool/pptx-to-pdf',
    '/pdf-tool/mht-to-pdf',
    '/pdf-tool/pdf-to-jpg',
    '/pdf-tool/pdf-to-word',
  ];

  // remove duplicates automatically
  const uniqueRoutes = [...new Set(routes)];

  return uniqueRoutes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: route === '' ? 1 : 0.8,
  }));
}

