import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer - AI Online Tools",
  description:
    "Disclaimer information for AI Online Tools regarding the use of its developer tools and services.",
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-5xl mx-auto px-6 py-16">

      <h1 className="text-4xl font-bold mb-6">Disclaimer</h1>

      <p className="text-gray-600 mb-6">
        The information and tools provided on AI Online Tools are offered for
        general informational and development purposes only.
      </p>

      <p className="text-gray-600 mb-6">
        While we strive to ensure accuracy and reliability, we make no
        guarantees regarding the correctness or completeness of the results
        generated by the tools.
      </p>

      <p className="text-gray-600">
        Users are responsible for verifying results before using them in
        production environments.
      </p>

    </div>
  );
}